// Get data of selected model
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

// Get data of selected model
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_PRODUCT_SUCCESS = "SET_PRODUCT_SUCCESS";
export const SET_PRODUCT_FAILURE = "SET_PRODUCT_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

// GET DETAILS
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";

// GET FILTERED DEETS
export const GET_FILTER_PRODUCT = "GET_FILTER_PRODUCT";
export const GET_FILTER_PRODUCT_SUCCESS = "GET_FILTER_PRODUCT_SUCCESS";
export const GET_FILTER_PRODUCT_FAILURE = "GET_FILTER_PRODUCT_FAILURE";

// DAVID- RESET FILTER_PRODUCT & SINGLE SKU RESET
export const GET_FILTER_PRODUCT_AND_SINGLE_SKU_RESET ="GET_FILTER_PRODUCT_AND_SINGLE_SKU_RESET";

// David - GET - SKUProductbyID
export const GET_SINGLE_SKU_PRODUCT_REQUEST = "GET_SINGLE_SKU_PRODUCT_REQUEST";
export const GET_SINGLE_SKU_PRODUCT_SUCCESS = "GET_SINGLE_SKU_PRODUCT_SUCCESS";
export const GET_SINGLE_SKU_PRODUCT_FAILURE = "GET_SINGLE_SKU_PRODUCT_FAILURE";

// David - PATCH- SKUProductbyID | Update
export const PATCH_SINGLE_SKU_PRODUCT_REQUEST = "PATCH_SINGLE_SKU_PRODUCT_REQUEST";
export const PATCH_SINGLE_SKU_PRODUCT_SUCCESS = "PATCH_SINGLE_SKU_PRODUCT_SUCCESS";
export const PATCH_SINGLE_SKU_PRODUCT_FAILURE = "PATCH_SINGLE_SKU_PRODUCT_FAILURE";

// DELETE SKU DETAILS
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

// BOM
export const SET_BOM = "SET_BOM";
export const SET_BOM_SUCCESS = "SET_BOM_SUCCESS";
export const SET_BOM_FAILURE = "SET_BOM_FAILURE";

// LOCATION
export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE";

//Sku
export const PATCH_SINGLE_SKU = "PATCH_SINGLE_SKU";
export const PATCH_SINGLE_SKU_SUCCESS = "PATCH_SINGLE_SKU_SUCCESS";
export const PATCH_SINGLE_SKU_FAILURE = "PATCH_SINGLE_SKU_FAILURE";

// stock split/move
export const CREATE_STOCK_MOVE_SKU = "CREATE_STOCK_MOVE_SKU";
export const CREATE_STOCK_MOVE_SKU_FAILURE = "CREATE_STOCK_MOVE_SKU_FAILURE";
export const CREATE_STOCK_MOVE_SKU_SUCCESS = "CREATE_STOCK_MOVE_SKU_SUCCESS";

// stockMerge 
export const PATCH_STOCK_MERGE_SKU = "PATCH_STOCK_MERGE_SKU";
export const PATCH_STOCK_MERGE_SKU_SUCCESS = "PATCH_STOCK_MERGE_SKU_SUCCESS";
export const PATCH_STOCK_MERGE_SKU_FAILURE = "PATCH_STOCK_MERGE_SKU_FAILURE";

// CSV GENERATOR 
export const CSV_CREATE_PRODUCT_SKU = "CSV_CREATE_PRODUCT_SKU";
export const CSV_CREATE_PRODUCT_SKU_SUCCESS = "CSV_CREATE_PRODUCT_SKU_SUCCESS";
export const CSV_CREATE_PRODUCT_SKU_FAILURE = "CSV_CREATE_PRODUCT_SKU_FAILURE";

// add stock adjustment create journal entry 
export const POST_ADD_STOCK_CREATE_JOURNAL_ENTRY = "POST_ADD_STOCK_CREATE_JOURNAL_ENTRY";
export const POST_ADD_STOCK_CREATE_JOURNAL_ENTRY_SUCCESS = "POST_ADD_STOCK_CREATE_JOURNAL_ENTRY_SUCCESS";
export const POST_ADD_STOCK_CREATE_JOURNAL_ENTRY_FAILURE = "POST_ADD_STOCK_CREATE_JOURNAL_ENTRY_FAILURE";     


// deduct stock adjustment remove journal entry 
export const POST_DEDUCT_STOCK_CREATE_JOURNAL_ENTRY = "POST_DEDUCT_STOCK_CREATE_JOURNAL_ENTRY";
export const POST_DEDUCT_STOCK_CREATE_JOURNAL_ENTRY_SUCCESS = "POST_STOCK_PRODUCT_CREATE_JOURNAL_ENTRY_SUCCESS";
export const POST_DEDUCT_STOCK_CREATE_JOURNAL_ENTRY_FAILURE = "POST_STOCK_PRODUCT_CREATE_JOURNAL_ENTRY_FAILURE";     

//SAVE QUERIES FOR INVENTORY ENQUIRY
export const GET_SAVED_INVENTORY_QUERY = 'GET_SAVED_INVENTORY_QUERY';
export const GET_SAVED_INVENTORY_QUERY_SUCCESS = 'GET_SAVED_INVENTORY_QUERY_SUCCESS';
export const GET_SAVED_INVENTORY_QUERY_FAILURE = 'GET_SAVED_INVENTORY_QUERY_FAILURE';

//SAVE QUERIES FOR SKU LIST
export const GET_SAVED_SKU_LIST_QUERY = 'GET_SAVED_SKU_LIST_QUERY';
export const GET_SAVED_SKU_LIST_QUERY_SUCCESS = 'GET_SAVED_SKU_LIST_QUERY_SUCCESS';
export const GET_SAVED_SKU_LIST_QUERY_FAILURE = 'GET_SAVED_SKU_LIST_QUERY_FAILURE';

//SAVE QUERIES FOR SKU MAINTENANCE
export const GET_SAVED_SKU_MAIN_QUERY = 'GET_SAVED_SKU_MAIN_QUERY';
export const GET_SAVED_SKU_MAIN_QUERY_SUCCESS = 'GET_SAVED_SKU_MAIN_QUERY_SUCCESS';
export const GET_SAVED_SKU_MAIN_QUERY_FAILURE = 'GET_SAVED_SKU_MAIN_QUERY_FAILURE';

//SAVE QUERIES FOR STOCK ADJUSTMENT
export const GET_SAVED_STOCK_ADJ_QUERY = 'GET_SAVED_STOCK_ADJ_QUERY';
export const GET_SAVED_STOCK_ADJ_QUERY_SUCCESS = 'GET_SAVED_STOCK_ADJ_QUERY_SUCCESS';
export const GET_SAVED_STOCK_ADJ_QUERY_FAILURE = 'GET_SAVED_STOCK_ADJ_QUERY_FAILURE';