// GET all DOWN_PAYMENTs
export const GET_ALL_DOWN_PAYMENTS = "GET_ALL_DOWN_PAYMENTS";
export const GET_ALL_DOWN_PAYMENTS_SUCCESS = "GET_ALL_DOWN_PAYMENTS_SUCCESS";
export const GET_ALL_DOWN_PAYMENTS_FAILURE = "GET_ALL_DOWN_PAYMENTS_FAILURE";

// GET one DOWN_PAYMENT
export const GET_DOWN_PAYMENT = "GET_DOWN_PAYMENT";
export const GET_DOWN_PAYMENT_SUCCESS = "GET_DOWN_PAYMENT_SUCCESS";
export const GET_DOWN_PAYMENT_FAILURE = "GET_DOWN_PAYMENT_FAILURE";

// POST one DOWN_PAYMENT 
export const POST_DOWN_PAYMENT = "POST_DOWN_PAYMENT";
export const POST_DOWN_PAYMENT_SUCCESS = "POST_DOWN_PAYMENT_SUCCESS";
export const POST_DOWN_PAYMENT_FAILURE = "POST_DOWN_PAYMENT_FAILURE";

// PATCH one DOWN_PAYMENT 
export const PATCH_DOWN_PAYMENT = "PATCH_DOWN_PAYMENT";
export const PATCH_DOWN_PAYMENT_SUCCESS = "PATCH_DOWN_PAYMENT_SUCCESS";
export const PATCH_DOWN_PAYMENT_FAILURE = "PATCH_DOWN_PAYMENT_FAILURE";

// DELETE one DOWN_PAYMENT  
export const DELETE_DOWN_PAYMENT = "DELETE_DOWN_PAYMENT";
export const DELETE_DOWN_PAYMENT_SUCCESS = "DELETE_DOWN_PAYMENT_SUCCESS";
export const DELETE_DOWN_PAYMENT_FAILURE = "DELETE_DOWN_PAYMENT_FAILURE";
