export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const USER_RIGHTS = "USER_RIGHTS";
export const USER_RIGHTS_SUCCESS = "USER_RIGHTS_SUCCESS";
export const USER_RIGHTS_FAILURE = "USER_RIGHTS_FAILURE";

// Edit User
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";
export const UPDATE_CURRENT_USER_FAILURE = "UPDATE_CURRENT_USER_FAILURE";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const GET_USER_MY_PROFILE = "GET_USER_MY_PROFILE";
export const GET_USER_MY_PROFILE_SUCCESS = "GET_USER_MY_PROFILE_SUCCESS";
export const GET_USER_MY_PROFILE_FAILURE = "GET_USER_MY_PROFILE_FAILURE";


// Movement Out data of selected model
export const MOVEMENT_OUT_USER = "MOVEMENT_OUT_USER";
export const MOVEMENT_OUT_USER_SUCCESS = "MOVEMENT_OUT_USER_SUCCESS";
export const MOVEMENT_OUT_USER_FAILURE = "MOVEMENT_OUT_USER_FAILURE";
