// GET all BALANCE_SHEET
export const GET_ALL_BALANCE_SHEET = "GET_ALL_BALANCE_SHEET";
export const GET_ALL_BALANCE_SHEET_SUCCESS = "GET_ALL_BALANCE_SHEET_SUCCESS";
export const GET_ALL_BALANCE_SHEET_FAILURE = "GET_ALL_BALANCE_SHEET_FAILURE";

// GET one BALANCE_SHEET
export const GET_BALANCE_SHEET = "GET_BALANCE_SHEET";
export const GET_BALANCE_SHEET_SUCCESS = "GET_BALANCE_SHEET_SUCCESS";
export const GET_BALANCE_SHEET_FAILURE = "GET_BALANCE_SHEET_FAILURE";

// POST one BALANCE_SHEET 
export const POST_BALANCE_SHEET = "POST_BALANCE_SHEET";
export const POST_BALANCE_SHEET_SUCCESS = "POST_BALANCE_SHEET_SUCCESS";
export const POST_BALANCE_SHEET_FAILURE = "POST_BALANCE_SHEET_FAILURE";

// PATCH one BALANCE_SHEET 
export const PATCH_BALANCE_SHEET = "PATCH_BALANCE_SHEET";
export const PATCH_BALANCE_SHEET_SUCCESS = "PATCH_BALANCE_SHEET_SUCCESS";
export const PATCH_BALANCE_SHEET_FAILURE = "PATCH_BALANCE_SHEET_FAILURE";

// DELETE one BALANCE_SHEET  
export const DELETE_BALANCE_SHEET = "DELETE_BALANCE_SHEET";
export const DELETE_BALANCE_SHEET_SUCCESS = "DELETE_BALANCE_SHEET_SUCCESS";
export const DELETE_BALANCE_SHEET_FAILURE = "DELETE_BALANCE_SHEET_FAILURE";