// Get data of selected model
export const GET_CREDIT_NOTE = "GET_CREDIT_NOTE";
export const GET_CREDIT_NOTE_SUCCESS = "GET_CREDIT_NOTE_SUCCESS";
export const GET_CREDIT_NOTE_FAILURE = "GET_CREDIT_NOTE_FAILURE";

// Get data of selected model
export const SET_CREDIT_NOTE = "SET_CREDIT_NOTE";
export const SET_CREDIT_NOTE_SUCCESS = "SET_CREDIT_NOTE_SUCCESS";
export const SET_CREDIT_NOTE_FAILURE = "SET_CREDIT_NOTE_FAILURE";

// GET DETAILS
export const GET_DROPDOWN_GROUP = "GET_DROPDOWN_GROUP";
export const GET_DROPDOWN_GROUP_SUCCESS = "GET_DROPDOWN_GROUP_SUCCESS";
export const GET_DROPDOWN_GROUP_FAILURE = "GET_DROPDOWN_GROUP_FAILURE";

// GET FILTERS
export const GET_FILTER_CREDIT_NOTE = "GET_FILTER_CREDIT_NOTE";
export const GET_FILTER_CREDIT_NOTE_SUCCESS = "GET_FILTER_CREDIT_NOTE_SUCCESS";
export const GET_FILTER_CREDIT_NOTE_FAILURE = "GET_FILTER_CREDIT_NOTE_FAILURE";

// DELETE CREDIT_NOTE
export const DELETE_CREDIT_NOTE = "DELETE_CREDIT_NOTE";
export const DELETE_CREDIT_NOTE_SUCCESS = "DELETE_CREDIT_NOTE_SUCCESS";
export const DELETE_CREDIT_NOTE_FAILURE = "DELETE_CREDIT_NOTE_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

//get single invoice
export const GET_SINGLE_CREDIT_NOTE_REQUEST = "GET_SINGLE_CREDIT_NOTE_REQUEST";
export const GET_SINGLE_CREDIT_NOTE_REQUEST_SUCCESS = "GET_SINGLE_CREDIT_NOTE_REQUEST_SUCCESS";
export const GET_SINGLE_CREDIT_NOTE_REQUEST_FAILURE = "GET_SINGLE_CREDIT_NOTE_REQUEST_FAILURE";

//patch single invoice
export const PATCH_SINGLE_CREDIT_NOTE = "PATCH_SINGLE_CREDIT_NOTE";
export const PATCH_SINGLE_CREDIT_NOTE_SUCCESS = "PATCH_SINGLE_CREDIT_NOTE_SUCCESS";
export const PATCH_SINGLE_CREDIT_NOTE_FAILURE = "PATCH_SINGLE_CREDIT_NOTE_FAILURE";

// get pdf
export const GET_CREDIT_NOTE_PDF = "GET_CREDIT_NOTE_PDF";
export const GET_CREDIT_NOTE_PDF_SUCCESS = "GET_CREDIT_NOTE_PDF_SUCCESS";
export const GET_CREDIT_NOTE_PDF_FAILURE = "GET_CREDIT_NOTE_PDF_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_CREDIT_NOTE_QUERY = 'GET_SAVED_CREDIT_NOTE_QUERY';
export const GET_SAVED_CREDIT_NOTE_QUERY_SUCCESS = 'GET_SAVED_CREDIT_NOTE_QUERY_SUCCESS';
export const GET_SAVED_CREDIT_NOTE_QUERY_FAILURE = 'GET_SAVED_CREDIT_NOTE_QUERY_FAILURE';

