// GET all discount 
export const GET_ALL_DISCOUNTS = "GET_ALL_DISCOUNTS";
export const GET_ALL_DISCOUNTS_SUCCESS = "GET_ALL_DISCOUNTS_SUCCESS";
export const GET_ALL_DISCOUNTS_FAILURE = "GET_ALL_DISCOUNTS_FAILURE";

// GET one discount
export const GET_DISCOUNT = "GET_DISCOUNT";
export const GET_DISCOUNT_SUCCESS = "GET_DISCOUNT_SUCCESS";
export const GET_DISCOUNT_FAILURE = "GET_DISCOUNT_FAILURE";

// POST one discount
export const POST_DISCOUNT = "POST_DISCOUNT";
export const POST_DISCOUNT_SUCCESS = "POST_DISCOUNT_SUCCESS";
export const POST_DISCOUNT_FAILURE = "POST_DISCOUNT_FAILURE";

// PUT one stock location 
export const PUT_DISCOUNT = "PUT_DISCOUNT";
export const PUT_DISCOUNT_SUCCESS = "PUT_DISCOUNT_SUCCESS";
export const PUT_DISCOUNT_FAILURE = "PUT_DISCOUNT_FAILURE";

// DELETE one stock location  
export const DELETE_DISCOUNT = "DELETE_DISCOUNT";
export const DELETE_DISCOUNT_SUCCESS = "DELETE_DISCOUNT_SUCCESS";
export const DELETE_DISCOUNT_FAILURE = "DELETE_DISCOUNT_FAILURE"; 