// GET all CREDIT_LIMITs
export const GET_ALL_CREDIT_LIMITS = "GET_ALL_CREDIT_LIMITS";
export const GET_ALL_CREDIT_LIMITS_SUCCESS = "GET_ALL_CREDIT_LIMITS_SUCCESS";
export const GET_ALL_CREDIT_LIMITS_FAILURE = "GET_ALL_CREDIT_LIMITS_FAILURE";

// GET one CREDIT_LIMIT
export const GET_CREDIT_LIMIT = "GET_CREDIT_LIMIT";
export const GET_CREDIT_LIMIT_SUCCESS = "GET_CREDIT_LIMIT_SUCCESS";
export const GET_CREDIT_LIMIT_FAILURE = "GET_CREDIT_LIMIT_FAILURE";

// POST one CREDIT_LIMIT 
export const POST_CREDIT_LIMIT = "POST_CREDIT_LIMIT";
export const POST_CREDIT_LIMIT_SUCCESS = "POST_CREDIT_LIMIT_SUCCESS";
export const POST_CREDIT_LIMIT_FAILURE = "POST_CREDIT_LIMIT_FAILURE";

// PATCH one CREDIT_LIMIT 
export const PATCH_CREDIT_LIMIT = "PATCH_CREDIT_LIMIT";
export const PATCH_CREDIT_LIMIT_SUCCESS = "PATCH_CREDIT_LIMIT_SUCCESS";
export const PATCH_CREDIT_LIMIT_FAILURE = "PATCH_CREDIT_LIMIT_FAILURE";

// DELETE one CREDIT_LIMIT  
export const DELETE_CREDIT_LIMIT = "DELETE_CREDIT_LIMIT";
export const DELETE_CREDIT_LIMIT_SUCCESS = "DELETE_CREDIT_LIMIT_SUCCESS";
export const DELETE_CREDIT_LIMIT_FAILURE = "DELETE_CREDIT_LIMIT_FAILURE";
