export const GET_ALL_DELIVERYORDER = 'GET_ALL_DELIVERYORDER'
export const GET_ALL_DELIVERYORDER_SUCCESS = 'GET_ALL_DELIVERYORDER_SUCCESS'
export const GET_ALL_DELIVERYORDER_FAILURE = 'GET_ALL_DELIVERYORDER_FAILURE'

export const GET_FILTER_DELIVERYORDER_REQUEST = 'GET_FILTER_DELIVERYORDER_REQUEST'
export const GET_FILTER_DELIVERYORDER_SUCCESS = 'GET_FILTER_DELIVERYORDER_SUCCESS'
export const GET_FILTER_DELIVERYORDER_FAILURE = 'GET_FILTER_DELIVERYORDER_FAILURE'

export const GET_DELIVERYORDER = 'GET_DELIVERYORDER'
export const GET_DELIVERYORDER_SUCCESS = 'GET_DELIVERYORDER_SUCCESS'
export const GET_DELIVERYORDER_FAILURE = 'GET_DELIVERYORDER_FAILURE'

export const SET_DELIVERYORDER_ITEM = 'SET_DELIVERYORDER_ITEM'
export const SET_DELIVERYORDER_ITEM_SUCCESS = 'SET_DELIVERYORDER_ITEM_SUCCESS'
export const SET_DELIVERYORDER_ITEM_FAILURE = 'SET_DELIVERYORDER_ITEM_FAILURE'

export const DELETE_DELIVERYORDER_ITEM = 'DELETE_DELIVERYORDER_ITEM'
export const DELETE_DELIVERYORDER_ITEM_SUCCESS = 'DELETE_DELIVERYORDER_ITEM_SUCCESS'
export const DELETE_DELIVERYORDER_ITEM_FAILURE = 'DELETE_DELIVERYORDER_ITEM_FAILURE'

export const SET_DELIVERYORDER_ITEM_FROM_PACKING_LIST = 'SET_DELIVERYORDER_ITEM_FROM_PACKING_LIST';
export const SET_DELIVERYORDER_ITEM_FROM_PACKING_LIST_SUCCESS = 'SET_DELIVERYORDER_ITEM_FROM_PACKING_LIST_SUCCESS';
export const SET_DELIVERYORDER_ITEM_FROM_PACKING_LIST_FAILURE = 'SET_DELIVERYORDER_ITEM_FROM_PACKING_LIST_FAILURE';
export const RESET_DELIVERYORDER_ITEM_FROM_PACKING_LIST = 'RESET_DELIVERYORDER_ITEM_FROM_PACKING_LIST';


export const PATCH_DELIVERYORDER_ITEM = 'PATCH_DELIVERYORDER_ITEM'
export const PATCH_DELIVERYORDER_ITEM_SUCCESS = 'PATCH_DELIVERYORDER_ITEM_SUCCESS'
export const PATCH_DELIVERYORDER_ITEM_FAILURE = 'PATCH_DELIVERYORDER_ITEM_FAILURE'

// CREATE PDF
export const PDF_CREATE_DELIVERY_ORDER = 'PDF_CREATE_DELIVERY_ORDER';
export const PDF_CREATE_DELIVERY_ORDER_SUCCESS = 'PDF_CREATE_DELIVERY_ORDER_SUCCESS';
export const PDF_CREATE_DELIVERY_ORDER_FAILURE = 'PDF_CREATE_DELIVERY_ORDER_FAILURE';

//SAVE QUERIES 
export const GET_SAVED_DELIVERY_ORDER_QUERY = 'GET_SAVED_DELIVERY_ORDER_QUERY';
export const GET_SAVED_DELIVERY_ORDER_QUERY_SUCCESS = 'GET_SAVED_DELIVERY_ORDER_QUERY_SUCCESS';
export const GET_SAVED_DELIVERY_ORDER_QUERY_FAILURE = 'GET_SAVED_DELIVERY_ORDER_QUERY_FAILURE';
