// Get data of selected model
export const GET_PURCHASE = "GET_PURCHASE";
export const GET_PURCHASE_SUCCESS = "GET_PURCHASE_SUCCESS";
export const GET_PURCHASE_FAILURE = "GET_PURCHASE_FAILURE";

// Get data of selected model
export const SET_PURCHASE = "SET_PURCHASE";
export const SET_PURCHASE_SUCCESS = "SET_PURCHASE_SUCCESS";
export const SET_PURCHASE_FAILURE = "SET_PURCHASE_FAILURE";

// GET DETAILS
export const GET_PURCHASE_DETAILS = "GET_PURCHASE_DETAILS";
export const GET_PURCHASE_DETAILS_SUCCESS = "GET_PURCHASE_DETAILS_SUCCESS";
export const GET_PURCHASE_DETAILS_FAILURE = "GET_PURCHASE_DETAILS_FAILURE";

// GET FILTERED DEETS
export const GET_FILTER_PURCHASE = "GET_FILTER_PURCHASE";
export const GET_FILTER_PURCHASE_SUCCESS = "GET_FILTER_PURCHASE_SUCCESS";
export const GET_FILTER_PURCHASE_FAILURE = "GET_FILTER_PURCHASE_FAILURE";

// DELETE SKU DETAILS
export const DELETE_PURCHASE = "DELETE_PURCHASE";
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_FAILURE = "DELETE_PURCHASE_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";
// David - GET - SINGLE  BY ID
export const GET_SINGLE_PURCHASE_REQUEST = "GET_SINGLE_PURCHASE_REQUEST";
export const GET_SINGLE_PURCHASE_SUCCESS = "GET_SINGLE_PURCHASE_SUCCESS";
export const GET_SINGLE_PURCHASE_FAILURE = "GET_SINGLE_PURCHASE_FAILURE";

// David - PATCH - SINGLE PURCHASE BY ID
export const PATCH_SINGLE_PURCHASE_REQUEST = "PATCH_SINGLE_PURCHASE_REQUEST";
export const PATCH_SINGLE_PURCHASE_SUCCESS = "PATCH_SINGLE_PURCHASE_SUCCESS";
export const PATCH_SINGLE_PURCHASE_FAILURE = "PATCH_SINGLE_PURCHASE_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

export const PDF_CREATE_PURCHASE_ORDER = 'PDF_CREATE_PURCHASE_ORDER';
export const PDF_CREATE_PURCHASE_ORDER_SUCCESS = 'PDF_CREATE_PURCHASE_ORDER_SUCCESS';
export const PDF_CREATE_PURCHASE_ORDER_FAILURE = 'PDF_CREATE_SALES_PURCHASE_ORDER_FAILURE' ;

// patch internal remarks for single purchase on dashboard 
export const PATCH_SINGLE_PURCHASE_REQUEST_INTERNAL_REMARKS = "PATCH_SINGLE_PURCHASE_REQUEST_INTERNAL_REMARKS";
export const PATCH_SINGLE_PURCHASE_REQUEST_INTERNAL_REMARKS_SUCCESS = "PATCH_SINGLE_PURCHASE_INTERNAL_REMARKS_SUCCESS";
export const PATCH_SINGLE_PURCHASE_REQUEST_INTERNAL_REMARKS_FAILURE = "PATCH_SINGLE_PURCHASE_INTERNAL_REMARKS_FAILURE";


//SAVE QUERIES 
export const GET_SAVED_PURCHASE_QUERY = 'GET_SAVED_PURCHASE_QUERY';
export const GET_SAVED_PURCHASE_QUERY_SUCCESS = 'GET_SAVED_PURCHASE_QUERY_SUCCESS';
export const GET_SAVED_PURCHASE_QUERY_FAILURE = 'GET_SAVED_PURCHASE_QUERY_FAILURE';