// GET ALL LOANS
export  const GET_ALL_LONG_TERM_LOANS ="GET_ALL_LONG_TERM_LOANS" ;
export  const GET_ALL_LONG_TERM_LOANS_SUCCESS ="GET_ALL_LONG_TERM_LOANS_SUCCESS";
export  const GET_ALL_LONG_TERM_LOANS_FAILURE = "GET_ALL_LONG_TERM_LOANS_FAILURE";
export  const GET_ALL_SHORT_TERM_LOANS ="GET_ALL_SHORT_TERM_LOANS" ;
export  const GET_ALL_SHORT_TERM_LOANS_SUCCESS ="GET_ALL_SHORT_TERM_LOANS_SUCCESS";
export  const GET_ALL_SHORT_TERM_LOANS_FAILURE = "GET_ALL_SHORT_TERM_LOANS_FAILURE";


// GET SINGLE LOAN
export const GET_SINGLE_LONG_TERM_LOAN ="GET_SINGLE_LONG_TERM_LOAN";
export const GET_SINGLE_LONG_TERM_LOAN_SUCCESS ="GET_SINGLE_LONG_TERM_LOAN_SUCCESS";
export const GET_SINGLE_LONG_TERM_LOAN_FAILURE ="GET_SINGLE_LONG_TERM_LOAN_FAILURE";
export const GET_SINGLE_SHORT_TERM_LOAN ="GET_SINGLE_SHORT_TERM_LOAN";
export const GET_SINGLE_SHORT_TERM_LOAN_SUCCESS ="GET_SINGLE_SHORT_TERM_LOAN_SUCCESS";
export const GET_SINGLE_SHORT_TERM_LOAN_FAILURE ="GET_SINGLE_SHORT_TERM_LOAN_FAILURE";


// POET SINGLE LOAN
export const POST_SINGLE_LONG_TERM_LOAN ="POST_SINGLE_LONG_TERM_LOAN";
export const POST_SINGLE_LONG_TERM_LOAN_SUCCESS ="POST_SINGLE_LONG_TERM_LOAN_SUCCESS";
export const POST_SINGLE_LONG_TERM_LOAN_FAILURE ="POST_SINGLE_LONG_TERM_LOAN_FAILURE";
export const POST_SINGLE_SHORT_TERM_LOAN ="POST_SINGLE_SHORT_TERM_LOAN";
export const POST_SINGLE_SHORT_TERM_LOAN_SUCCESS ="POST_SINGLE_SHORT_TERM_LOAN_SUCCESS";
export const POST_SINGLE_SHORT_TERM_LOAN_FAILURE ="POST_SINGLE_SHORT_TERM_LOAN_FAILURE";


// PATCH SINGLE LOAN
export const PATCH_SINGLE_LONG_TERM_LOAN ="PATCH_SINGLE_LONG_TERM_LOAN";
export const PATCH_SINGLE_LONG_TERM_LOAN_SUCCESS ="PATCH_SINGLE_LONG_TERM_LOAN_SUCCESS";
export const PATCH_SINGLE_LONG_TERM_LOAN_FAILURE ="PATCH_SINGLE_LONG_TERM_LOAN_FAILURE";
export const PATCH_SINGLE_SHORT_TERM_LOAN ="PATCH_SINGLE_SHORT_TERM_LOAN";
export const PATCH_SINGLE_SHORT_TERM_LOAN_SUCCESS ="PATCH_SINGLE_SHORT_TERM_LOAN_SUCCESS";
export const PATCH_SINGLE_SHORT_TERM_LOAN_FAILURE ="PATCH_SINGLE_SHORT_TERM_LOAN_FAILURE";

// DELETE SINGLE LOAN
export const DELETE_LONG_TERM_LOAN ="DELETE_LONG_TERM_LOAN";
export const DELETE_LONG_TERM_LOAN_SUCCESS ="DELETE_LONG_TERM_LOAN_SUCCESS";
export const DELETE_LONG_TERM_LOAN_FAILURE ="DELETE_LONG_TERM_LOAN__FAILURE";
export const DELETE_SHORT_TERM_LOAN ="DELETE_SHORT_TERM_LOAN";
export const DELETE_SHORT_TERM_LOAN_SUCCESS ="DELETE_SHORT_TERM_LOAN_SUCCESS";
export const DELETE_SHORT_TERM_LOAN_FAILURE ="DELETE_SHORT_TERM_LOAN_FAILURE";

//SAVE QUERIES FOR SHORT TERM LOAN
export const GET_SAVED_SHORT_LOAN_QUERY = 'GET_SAVED_SHORT_LOAN_QUERY';
export const GET_SAVED_SHORT_LOAN_QUERY_SUCCESS = 'GET_SAVED_SHORT_LOAN_QUERY_SUCCESS';
export const GET_SAVED_SHORT_LOAN_QUERY_FAILURE = 'GET_SAVED_SHORT_LOAN_QUERY_FAILURE';

//SAVE QUERIES FOR LONG TERM LOAN
export const GET_SAVED_LONG_LOAN_QUERY = 'GET_SAVED_LONG_LOAN_QUERY';
export const GET_SAVED_LONG_LOAN_QUERY_SUCCESS = 'GET_SAVED_LONG_LOAN_QUERY_SUCCESS';
export const GET_SAVED_LONG_LOAN_QUERY_FAILURE = 'GET_SAVED_LONG_LOAN_QUERY_FAILURE';
