// Get Generating Report Data
export const GET_GENERATING_REPORT = "GET_GENERATING_REPORT";
export const GET_GENERATING_REPORT_SUCCESS = "GET_GENERATING_REPORT_SUCCESS";
export const GET_GENERATING_REPORT_FAILURE = "GET_GENERATING_REPORT_FAILURE";