// GET all CURRENCYs
export const GET_ALL_CURRENCES = "GET_ALL_CURRENCES";
export const GET_ALL_CURRENCES_SUCCESS = "GET_ALL_CURRENCES_SUCCESS";
export const GET_ALL_CURRENCES_FAILURE = "GET_ALL_CURRENCES_FAILURE";

// GET one CURRENCY
export const GET_CURRENCY = "GET_CURRENCY";
export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS";
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE";

// POST one CURRENCY 
export const POST_CURRENCY = "POST_CURRENCY";
export const POST_CURRENCY_SUCCESS = "POST_CURRENCY_SUCCESS";
export const POST_CURRENCY_FAILURE = "POST_CURRENCY_FAILURE";


// PATCH one CURRENCY 
export const PATCH_CURRENCY = "PATCH_CURRENCY";
export const PATCH_CURRENCY_SUCCESS = "PATCH_CURRENCY_SUCCESS";
export const PATCH_CURRENCY_FAILURE = "PATCH_CURRENCY_FAILURE";

// DELETE one CURRENCY  
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const DELETE_CURRENCY_SUCCESS = "DELETE_CURRENCY_SUCCESS";
export const DELETE_CURRENCY_FAILURE = "DELETE_CURRENCY_FAILURE";
