// Get data of selected model
export const GET_DEBIT_NOTE = "GET_DEBIT_NOTE";
export const GET_DEBIT_NOTE_SUCCESS = "GET_DEBIT_NOTE_SUCCESS";
export const GET_DEBIT_NOTE_FAILURE = "GET_DEBIT_NOTE_FAILURE";

// Get data of selected model
export const SET_DEBIT_NOTE = "SET_DEBIT_NOTE";
export const SET_DEBIT_NOTE_SUCCESS = "SET_DEBIT_NOTE_SUCCESS";
export const SET_DEBIT_NOTE_FAILURE = "SET_DEBIT_NOTE_FAILURE";


// GET FILTERS
export const GET_FILTER_DEBIT_NOTE = "GET_FILTER_DEBIT_NOTE";
export const GET_FILTER_DEBIT_NOTE_SUCCESS = "GET_FILTER_DEBIT_NOTE_SUCCESS";
export const GET_FILTER_DEBIT_NOTE_FAILURE = "GET_FILTER_DEBIT_NOTE_FAILURE";

// DELETE DEBIT_NOTE
export const DELETE_DEBIT_NOTE = "DELETE_DEBIT_NOTE";
export const DELETE_DEBIT_NOTE_SUCCESS = "DELETE_DEBIT_NOTE_SUCCESS";
export const DELETE_DEBIT_NOTE_FAILURE = "DELETE_DEBIT_NOTE_FAILURE";


//get single invoice
export const GET_SINGLE_DEBIT_NOTE_REQUEST = "GET_SINGLE_DEBIT_NOTE_REQUEST";
export const GET_SINGLE_DEBIT_NOTE_REQUEST_SUCCESS = "GET_SINGLE_DEBIT_NOTE_REQUEST_SUCCESS";
export const GET_SINGLE_DEBIT_NOTE_REQUEST_FAILURE = "GET_SINGLE_DEBIT_NOTE_REQUEST_FAILURE";

//patch single invoice
export const PATCH_SINGLE_DEBIT_NOTE = "PATCH_SINGLE_DEBIT_NOTE";
export const PATCH_SINGLE_DEBIT_NOTE_SUCCESS = "PATCH_SINGLE_DEBIT_NOTE_SUCCESS";
export const PATCH_SINGLE_DEBIT_NOTE_FAILURE = "PATCH_SINGLE_DEBIT_NOTE_FAILURE";

// get pdf
export const GET_DEBIT_NOTE_PDF = "GET_DEBIT_NOTE_PDF";
export const GET_DEBIT_NOTE_PDF_SUCCESS = "GET_DEBIT_NOTE_PDF_SUCCESS";
export const GET_DEBIT_NOTE_PDF_FAILURE = "GET_DEBIT_NOTE_PDF_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_DEBIT_NOTE_QUERY = 'GET_SAVED_DEBIT_NOTE_QUERY';
export const GET_SAVED_DEBIT_NOTE_QUERY_SUCCESS = 'GET_SAVED_DEBIT_NOTE_QUERY_SUCCESS';
export const GET_SAVED_DEBIT_NOTE_QUERY_FAILURE = 'GET_SAVED_DEBIT_NOTE_QUERY_FAILURE';

