// GET all FISCAL_YEARs
export const GET_ALL_FISCAL_YEARS = "GET_ALL_FISCAL_YEARS";
export const GET_ALL_FISCAL_YEARS_SUCCESS = "GET_ALL_FISCAL_YEARS_SUCCESS";
export const GET_ALL_FISCAL_YEARS_FAILURE = "GET_ALL_FISCAL_YEARS_FAILURE";

// GET all FISCAL_YEARs_By_Monthly
export const GET_ALL_FISCAL_YEARS_BY_MONTHLY = "GET_ALL_FISCAL_YEARS_BY_MONTHLY";
export const GET_ALL_FISCAL_YEARS_BY_MONTHLY_SUCCESS = "GET_ALL_FISCAL_YEARS_BY_MONTHLY_SUCCESS";
export const GET_ALL_FISCAL_YEARS_BY_MONTHLY_FAILURE = "GET_ALL_FISCAL_YEARS_BY_MONTHLY_FAILURE";

// GET one FISCAL_YEAR
export const GET_FISCAL_YEAR = "GET_FISCAL_YEAR";
export const GET_FISCAL_YEAR_SUCCESS = "GET_FISCAL_YEAR_SUCCESS";
export const GET_FISCAL_YEAR_FAILURE = "GET_FISCAL_YEAR_FAILURE";

// POST one FISCAL_YEAR 
export const POST_FISCAL_YEAR = "POST_FISCAL_YEAR";
export const POST_FISCAL_YEAR_SUCCESS = "POST_FISCAL_YEAR_SUCCESS";
export const POST_FISCAL_YEAR_FAILURE = "POST_FISCAL_YEAR_FAILURE";


// PATCH one FISCAL_YEAR 
export const PATCH_FISCAL_YEAR = "PATCH_FISCAL_YEAR";
export const PATCH_FISCAL_YEAR_SUCCESS = "PATCH_FISCAL_YEAR_SUCCESS";
export const PATCH_FISCAL_YEAR_FAILURE = "PATCH_FISCAL_YEAR_FAILURE";

// DELETE one FISCAL_YEAR  
export const DELETE_FISCAL_YEAR = "DELETE_FISCAL_YEAR";
export const DELETE_FISCAL_YEAR_SUCCESS = "DELETE_FISCAL_YEAR_SUCCESS";
export const DELETE_FISCAL_YEAR_FAILURE = "DELETE_FISCAL_YEAR_FAILURE";

//fiscal period
export const GET_ALL_FISCAL_PERIODS = "GET_ALL_FISCAL_PERIODS";
export const GET_ALL_FISCAL_PERIODS_SUCCESS = "GET_ALL_FISCAL_PERIODS_SUCCESS";
export const GET_ALL_FISCAL_PERIODS_FAILURE = "GET_ALL_FISCAL_PERIODS_FAILURE";

// GET all FISCAL_YEARs
export const GET_FISCAL_PERIOD_BY_MONTH = "GET_FISCAL_PERIOD_BY_MONTH";
export const GET_FISCAL_PERIOD_BY_MONTH_SUCCESS = "GET_FISCAL_PERIOD_BY_MONTH_SUCCESS";
export const GET_FISCAL_PERIOD_BY_MONTH_FAILURE = "GET_FISCAL_PERIOD_BY_MONTH_FAILURE";