export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

export const UPLOAD_MULTIPLE_FILE = "UPLOAD_MULTIPLE_FILE";
export const UPLOAD_MULTIPLE_FILE_SUCCESS = "UPLOAD_MULTIPLE_FILE_SUCCESS";
export const UPLOAD_MULTIPLE_FILE_FAILURE = "UPLOAD_MULTIPLE_FILE_FAILURE";

export const GET_UPLOAD_FILE = "GET_UPLOAD_FILE";
export const GET_UPLOAD_FILE_SUCCESS = "GET_UPLOAD_FILE_SUCCESS";
export const GET_UPLOAD_FILE_FAILURE = "GET_UPLOAD_FILE_FAILURE";

export const DELETE_UPLOAD_FILE = "DELETE_UPLOAD_FILE";
export const DELETE_UPLOAD_FILE_SUCCESS = "DELETE_UPLOAD_FILE_SUCCESS";
export const DELETE_UPLOAD_FILE_FAILURE = "DELETE_UPLOAD_FILE_FAILURE";

export const PATCH_UPLOAD_FILE = "PATCH_UPLOAD_FILE";
export const PATCH_UPLOAD_FILE_SUCCESS = "PATCH_UPLOAD_FILE_SUCCESS";
export const PATCH_UPLOAD_FILE_FAILURE = "PATCH_UPLOAD_FILE_FAILURE";

export const DOWNLOAD_UPLOAD_FILE = "DOWNLOAD_UPLOAD_FILE";
export const DOWNLOAD_UPLOAD_FILE_SUCCESS = "DOWNLOAD_UPLOAD_FILE_SUCCESS";
export const DOWNLOAD_UPLOAD_FILE_FAILURE = "DOWNLOAD_UPLOAD_FILE_FAILURE";