export const GET_ALL_STOCKS = "GET_ALL_STOCKS";
export const GET_ALL_STOCKS_FAILURE = "GET_ALL_STOCKS_FAILURE";
export const GET_ALL_STOCKS_SUCCESS = "GET_ALL_STOCKS_SUCCESS";

export const GET_FILTER_STOCKS = "GET_FILTER_STOCKS";
export const GET_FILTER_STOCKS_FAILURE = "GET_FILTER_STOCKS_FAILURE";
export const GET_FILTER_STOCKS_SUCCESS = "GET_FILTER_STOCKS_SUCCESS";

export const GET_MOVE_LINE = "GET_MOVE_LINE";
export const GET_MOVE_LINE_FAILURE = "GET_MOVE_LINE_FAILURE";
export const GET_MOVE_LINE_SUCCESS = "GET_MOVE_LINE_SUCCESS";

export const SAVE_OPERATION_FORM = "SAVE_OPERATION_FORM";
export const SAVE_OPERATION_FORM_FAILURE = "SAVE_OPERATION_FORM_FAILURE";
export const SAVE_OPERATION_FORM_SUCCESS = "SAVE_OPERATION_FORM_SUCCESS";

export const GET_FILTER_MOVES = "GET_FILTER_MOVES";
export const GET_FILTER_MOVES_FAILURE = "GET_FILTER_MOVES_FAILURE";
export const GET_FILTER_MOVES_SUCCESS = "GET_FILTER_MOVES_SUCCESS";

export const CREATE_STOCK_OPERATION = "CREATE_STOCK_OPERATION";
export const CREATE_STOCK_OPERATION_FAILURE = "CREATE_STOCK_OPERATION_FAILURE";
export const CREATE_STOCK_OPERATION_SUCCESS = "CREATE_STOCK_OPERATION_SUCCESS";

//SAVE QUERIES 
export const GET_SAVED_STOCK_QUERY = 'GET_SAVED_STOCK_QUERY';
export const GET_SAVED_STOCK_QUERY_SUCCESS = 'GET_SAVED_STOCK_QUERY_SUCCESS';
export const GET_SAVED_STOCK_QUERY_FAILURE = 'GET_SAVED_STOCK_QUERY_FAILURE';