// Get data of selected model
export const GET_QUOTATION = 'GET_QUOTATION'
export const GET_QUOTATION_SUCCESS = 'GET_QUOTATION_SUCCESS'
export const GET_QUOTATION_FAILURE = 'GET_QUOTATION_FAILURE'

// Get data of selected model
export const SET_QUOTATION = 'SET_QUOTATION'
export const SET_QUOTATION_SUCCESS = 'SET_QUOTATION_SUCCESS'
export const SET_QUOTATION_FAILURE = 'SET_QUOTATION_FAILURE'

// GET DETAILS
export const GET_QUOTATION_DETAILS = 'GET_QUOTATION_DETAILS'
export const GET_QUOTATION_DETAILS_SUCCESS = 'GET_QUOTATION_DETAILS_SUCCESS'
export const GET_QUOTATION_DETAILS_FAILURE = 'GET_QUOTATION_DETAILS_FAILURE'

// SET DUPLICATE
export const SET_DUPLICATE = 'SET_DUPLICATE'
export const SET_DUPLICATE_SUCCESS = 'SET_DUPLICATE_SUCCESS'
export const SET_DUPLICATE_FAILURE = 'SET_DUPLICATE_FAILURE'

// SET NEW VERSION
export const SET_NEW_VERSION_REQUEST = 'SET_NEW_VERSION_REQUEST'
export const SET_NEW_VERSION_SUCCESS = 'SET_NEW_VERSION_SUCCESS'
export const SET_NEW_VERSION_FAILURE = 'SET_NEW_VERSION_FAILURE'

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = 'CLEAR_DUPLICATE'
export const CLEAR_DUPLICATE_SUCCESS = 'CLEAR_DUPLICATE_SUCCESS'
export const CLEAR_DUPLICATE_FAILURE = 'CLEAR_DUPLICATE_FAILURE'

// FOCUS HERE ******************************
export const GET_FILTER_QUOTATION_REQUEST = 'GET_FILTER_QUOTATION_REQUEST'
export const GET_FILTER_QUOTATION_SUCCESS = 'GET_FILTER_QUOTATION_SUCCESS'
export const GET_FILTER_QUOTATION_FAILURE = 'GET_FILTER_QUOTATION_FAILURE'

// DAVID- RESET FILTER_QUOTATION & SINGLE SKU RESET
export const GET_FILTER_QUOTATION_AND_SINGLE_SKU_RESET =
  'GET_FILTER_QUOTATION_AND_SINGLE_SKU_RESET'

// David - GET - SKUQUOTATIONbyID
export const GET_SINGLE_SKU_QUOTATION_REQUEST =
  'GET_SINGLE_SKU_QUOTATION_REQUEST'
export const GET_SINGLE_SKU_QUOTATION_SUCCESS =
  'GET_SINGLE_SKU_QUOTATION_SUCCESS'
export const GET_SINGLE_SKU_QUOTATION_FAILURE =
  'GET_SINGLE_SKU_QUOTATION_FAILURE'

// David - PATCH- SKUQUOTATIONbyID | Update
export const PATCH_SINGLE_SKU_QUOTATION_REQUEST =
  'PATCH_SINGLE_SKU_QUOTATION_REQUEST'
export const PATCH_SINGLE_SKU_QUOTATION_SUCCESS =
  'PATCH_SINGLE_SKU_QUOTATION_SUCCESS'
export const PATCH_SINGLE_SKU_QUOTATION_FAILURE =
  'PATCH_SINGLE_SKU_QUOTATION_FAILURE'

// DELETE SKU DETAILS
export const DELETE_QUOTATION = 'DELETE_QUOTATION'
export const DELETE_QUOTATION_SUCCESS = 'DELETE_QUOTATION_SUCCESS'
export const DELETE_QUOTATION_FAILURE = 'DELETE_QUOTATION_FAILURE'

//PDF CREATE
export const PDF_CREATE_QUOTATION_ORDER = 'PDF_CREATE_QUOTATION_ORDER'
export const PDF_CREATE_QUOTATION_ORDER_SUCCESS = 'PDF_CREATE_QUOTATION_ORDER_SUCCESS'
export const PDF_CREATE_QUOTATION_ORDER_FAILURE = 'PDF_CREATE_QUOTATION_ORDER_FAILURE' 

//SAVE QUERIES 
export const GET_SAVED_QUOTATION_QUERY = 'GET_SAVED_QUOTATION_QUERY';
export const GET_SAVED_QUOTATION_QUERY_SUCCESS = 'GET_SAVED_QUOTATION_QUERY_SUCCESS';
export const GET_SAVED_QUOTATION_QUERY_FAILURE = 'GET_SAVED_QUOTATION_QUERY_FAILURE';

