export const GET_ALL_ACCOUNT_ITEM = "GET_ALL_ACCOUNT_ITEM";
export const GET_ALL_ACCOUNT_ITEM_FAILURE = "GET_ALL_ACCOUNT_ITEM_FAILURE";
export const GET_ALL_ACCOUNT_ITEM_SUCCESS = "GET_ALL_ACCOUNT_ITEM_SUCCESS";

export const GET_ONE_LINE = "GET_ONE_LINE";
export const GET_ONE_LINE_FAILURE = "GET_ONE_LINE_FAILURE";
export const GET_ONE_LINE_SUCCESS = "GET_ONE_LINE_SUCCESS";

export const CREATE_ACCOUNT_ITEM = "CREATE_ACCOUNT_ITEM";
export const CREATE_ACCOUNT_ITEM_FAILURE = "CREATE_ACCOUNT_ITEM_FAILURE";
export const CREATE_ACCOUNT_ITEM_SUCCESS = "CREATE_ACCOUNT_ITEM_SUCCESS";

export const PATCH_ACCOUNT_ITEM = "PATCH_ACCOUNT_ITEM";
export const PATCH_ACCOUNT_ITEM_FAILURE = "PATCH_ACCOUNT_ITEM_FAILURE";
export const PATCH_ACCOUNT_ITEM_SUCCESS = "PATCH_ACCOUNT_ITEM_SUCCESS";

export const DELETE_ACCOUNT_ITEM = "DELETE_ACCOUNT_ITEM";
export const DELETE_ACCOUNT_ITEM_FAILURE = "DELETE_ACCOUNT_ITEM_FAILURE";
export const DELETE_ACCOUNT_ITEM_SUCCESS = "DELETE_ACCOUNT_ITEM_SUCCESS";

export const GET_CURRENCY_DATA = "GET_CURRENCY_DATA";
export const GET_CURRENCY_DATA_FAILURE = "GET_CURRENCY_DATA_FAILURE";
export const GET_CURRENCY_DATA_SUCCESS = "GET_CURRENCY_DATA_SUCCESS";

//SAVE QUERIES 
export const GET_SAVED_ACCOUNT_QUERY = 'GET_SAVED_ACCOUNT_QUERY';
export const GET_SAVED_ACCOUNT_QUERY_SUCCESS = 'GET_SAVED_ACCOUNT_QUERY_SUCCESS';
export const GET_SAVED_ACCOUNT_QUERY_FAILURE = 'GET_SAVED_ACCOUNT_QUERY_FAILURE';
