// Get data of selected customer outstanding invoices
export const GET_FILTER_SUPPLIER_PAYMENT_REQUEST = "GET_FILTER_SUPPLIER_PAYMENT_REQUEST";
export const GET_FILTER_SUPPLIER_PAYMENT_REQUEST_SUCCESS = "GET_FILTER_SUPPLIER_PAYMENT_REQUEST_SUCCESS";
export const GET_FILTER_SUPPLIER_PAYMENT_REQUEST_FAILURE = "GET_FILTER_SUPPLIER_PAYMENT_REQUEST_FAILURE";

export const GET_SINGLE_SUPPLIER_PAYMENT_REQUEST = "GET_SINGLE_SUPPLIER_PAYMENT_REQUEST";
export const GET_SINGLE_SUPPLIER_PAYMENT_REQUEST_SUCCESS = "GET_SINGLE_SUPPLIER_PAYMENT_REQUEST_SUCCESS";
export const GET_SINGLE_SUPPLIER_PAYMENT_REQUEST_FAILURE = "GET_SINGLE_SUPPLIER_PAYMENT_REQUEST_FAILURE";

export const PATCH_SINGLE_SUPPLIER_PAYMENT = "PATCH_SINGLE_SUPPLIER_PAYMENT";
export const PATCH_SINGLE_SUPPLIER_PAYMENT_SUCCESS = "PATCH_SINGLE_SUPPLIER_PAYMENT_SUCCESS";
export const PATCH_SINGLE_SUPPLIER_PAYMENT_FAILURE = "PATCH_SINGLE_SUPPLIER_PAYMENT_FAILURE";

export const DELETE_SUPPLIER_PAYMENT = "DELETE_SUPPLIER_PAYMENT";
export const DELETE_SUPPLIER_PAYMENT_SUCCESS = "DELETE_SUPPLIER_PAYMENT_SUCCESS";
export const DELETE_SUPPLIER_PAYMENT_FAILURE = "DELETE_SUPPLIER_PAYMENT_FAILURE";

export const GET_OUTSTANDING_SUPPLIER_INVOICES = "GET_OUTSTANDING_SUPPLIER_INVOICES";
export const GET_OUTSTANDING_SUPPLIER_INVOICES_SUCCESS = "GET_OUTSTANDING_SUPPLIER_INVOICES_SUCCESS";
export const GET_OUTSTANDING_SUPPLIER_INVOICES_FAILURE = "GET_OUTSTANDING_SUPPLIER_INVOICES_FAILURE";

export const SET_SUPPLIER_PAYMENT = "SET_SUPPLIER_PAYMENT";
export const SET_SUPPLIER_PAYMENT_SUCCESS = "SET_SUPPLIER_PAYMENT_SUCCESS";
export const SET_SUPPLIER_PAYMENT_FAILURE = "SET_SUPPLIER_PAYMENT_FAILURE";

// CLEAR DATA LOADED FROM PREVIOUS FORM
export const CLEAR_DUPLICATE = 'CLEAR_DUPLICATE'
export const CLEAR_DUPLICATE_SUCCESS = 'CLEAR_DUPLICATE_SUCCESS'
export const CLEAR_DUPLICATE_FAILURE = 'CLEAR_DUPLICATE_FAILURE'

//SAVE QUERIES 
export const GET_SAVED_SUPPLIER_PAYMENT_QUERY = 'GET_SAVED_SUPPLIER_PAYMENT_QUERY';
export const GET_SAVED_SUPPLIER_PAYMENT_QUERY_SUCCESS = 'GET_SAVED_SUPPLIER_PAYMENT_QUERY_SUCCESS';
export const GET_SAVED_SUPPLIER_PAYMENT_QUERY_FAILURE = 'GET_SAVED_SUPPLIER_PAYMENT_QUERY_FAILURE';
