// GET all ADMIN_SETTING
export const GET_ALL_ADMIN_SETTING = "GET_ALL_ADMIN_SETTING";
export const GET_ALL_ADMIN_SETTING_SUCCESS = "GET_ALL_ADMIN_SETTING_SUCCESS";
export const GET_ALL_ADMIN_SETTING_FAILURE = "GET_ALL_ADMIN_SETTING_FAILURE";

// GET one ADMIN_SETTING
export const GET_ADMIN_SETTING = "GET_ADMIN_SETTING";
export const GET_ADMIN_SETTING_SUCCESS = "GET_ADMIN_SETTING_SUCCESS";
export const GET_ADMIN_SETTING_FAILURE = "GET_ADMIN_SETTING_FAILURE";

// POST one ADMIN_SETTING 
export const POST_ADMIN_SETTING = "POST_ADMIN_SETTING";
export const POST_ADMIN_SETTING_SUCCESS = "POST_ADMIN_SETTING_SUCCESS";
export const POST_ADMIN_SETTING_FAILURE = "POST_ADMIN_SETTING_FAILURE";

// PATCH one ADMIN_SETTING 
export const PATCH_ADMIN_SETTING = "PATCH_ADMIN_SETTING";
export const PATCH_ADMIN_SETTING_SUCCESS = "PATCH_ADMIN_SETTING_SUCCESS";
export const PATCH_ADMIN_SETTING_FAILURE = "PATCH_ADMIN_SETTING_FAILURE";

// DELETE one ADMIN_SETTING  
export const DELETE_ADMIN_SETTING = "DELETE_ADMIN_SETTING";
export const DELETE_ADMIN_SETTING_SUCCESS = "DELETE_ADMIN_SETTING_SUCCESS";
export const DELETE_ADMIN_SETTING_FAILURE = "DELETE_ADMIN_SETTING_FAILURE";

//Filter
export const GET_FILTER_ADMIN_SETTING = "GET_FILTER_ADMIN_SETTING";
export const GET_FILTER_ADMIN_SETTING_SUCCESS = "GET_FILTER_ADMIN_SETTING_SUCCESS";
export const GET_FILTER_ADMIN_SETTING_FAILURE = "GET_FILTER_ADMIN_SETTING_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_ADMIN_DUPLICATE = "CLEAR_ADMIN_DUPLICATE";
export const CLEAR_ADMIN_DUPLICATE_SUCCESS = "CLEAR_ADMIN_DUPLICATE_SUCCESS";
export const CLEAR_ADMIN_DUPLICATE_FAILURE = "CLEAR_ADMIN_DUPLICATE_FAILURE";