/**
 * Journal Actions
 */
export const GET_JOURNAL_LIST = "GET_JOURNAL_LIST";
export const GET_JOURNAL_LIST_SUCCESS = "GET_JOURNAL_LIST_SUCCESS";
export const GET_JOURNAL_LIST_FAILURE = "GET_JOURNAL_LIST_FAILURE";

export const DELETE_JOURNAL_ENTRY = "DELETE_JOURNAL_ENTRY";
export const DELETE_JOURNAL_ENTRY_SUCCESS = "DELETE_JOURNAL_ENTRY_SUCCESS";
export const DELETE_JOURNAL_ENTRY_FAILURE = "DELETE_JOURNAL_ENTRY_FAILURE";

export const GET_SINGLE_JOURNAL_ENTRY = "GET_SINGLE_JOURNAL_ENTRY";
export const GET_SINGLE_JOURNAL_ENTRY_SUCCESS = "GET_SINGLE_JOURNAL_ENTRY_SUCCESS";
export const GET_SINGLE_JOURNAL_ENTRY_FAILURE = "GET_SINGLE_JOURNAL_ENTRY_FAILURE";

export const GET_JOURNALS = "GET_JOURNALS";
export const GET_JOURNALS_SUCCESS = "GET_JOURNALS_SUCCESS";
export const GET_JOURNALS_FAILURE = "GET_JOURNALS_FAILURE";

export const CREATE_JOURNAL_ENTRY = "CREATE_JOURNAL_ENTRY";
export const CREATE_JOURNAL_ENTRY_SUCCESS = "CREATE_JOURNAL_ENTRY_SUCCESS";
export const CREATE_JOURNAL_ENTRY_FAILURE = "CREATE_JOURNAL_ENTRY_FAILURE";

export const UPDATE_JOURNAL_ENTRY = "UPDATE_JOURNAL_ENTRY";
export const UPDATE_JOURNAL_ENTRY_SUCCESS = "UPDATE_JOURNAL_ENTRY_SUCCESS";
export const UPDATE_JOURNAL_ENTRY_FAILURE = "UPDATE_JOURNAL_ENTRY_FAILURE";

// get filter
export const GET_FILTER_PARTNER_JOURNAL = "GET_FILTER_PARTNER_JOURNAL";
export const GET_FILTER_PARTNER_JOURNAL_SUCCESS = "GET_FILTER_PARTNER_JOURNAL_SUCCESS";
export const GET_FILTER_PARTNER_JOURNAL_FAILURE = "GET_FILTER_PARTNER_JOURNAL_FAILURE";

export const GET_FILTER_ACCOUNT_JOURNAL = "GET_FILTER_ACCOUNT_JOURNAL";
export const GET_FILTER_ACCOUNT_JOURNAL_SUCCESS = "GET_FILTER_ACCOUNT_JOURNAL_SUCCESS";
export const GET_FILTER_ACCOUNT_JOURNAL_FAILURE = "GET_FILTER_ACCOUNT_JOURNAL_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_JOURNAL_QUERY = 'GET_SAVED_JOURNAL_QUERY';
export const GET_SAVED_JOURNAL_QUERY_SUCCESS = 'GET_SAVED_JOURNAL_QUERY_SUCCESS';
export const GET_SAVED_JOURNAL_QUERY_FAILURE = 'GET_SAVED_JOURNAL_QUERY_FAILURE';

