

export const GET_ALL_WORKPICKING_ORDER = 'GET_ALL_WORKPICKING_ORDER'
export const GET_ALL_WORKPICKING_ORDER_SUCCESS = 'GET_ALL_WORKPICKING_ORDER_SUCCESS'
export const GET_ALL_WORKPICKING_ORDER_FAILURE = 'GET_ALL_WORKPICKING_ORDER_FAILURE'

// Get single work order 
export const POST_WORKPICKING_ORDER = 'POST_WORKPICKING_ORDER';
export const POST_WORKPICKING_ORDER_SUCCESS = 'POST_WORKPICKING_ORDER_SUCCESS';
export const POST_WORKPICKING_ORDER_FAILURE = 'POST_WORKPICKING_ORDER_FAILURE';

// update work order item 
export const SET_WORKPICKING_ORDER_ITEM = 'SET_WORKPICKING_ORDER_ITEM';
export const SET_WORKPICKING_ORDER_ITEM_SUCCESS = 'SET_WORKPICKING_ORDER_ITEM_SUCCESS';
export const SET_WORKPICKING_ORDER_ITEM_FAILURE = 'SET_WORKPICKING_ORDER_ITEM_FAILURE';