// Get data of selected model
export const GET_PAYMENT_DEPOSIT = "GET_PAYMENT_DEPOSIT";
export const GET_PAYMENT_DEPOSIT_SUCCESS = "GET_PAYMENT_DEPOSIT_SUCCESS";
export const GET_PAYMENT_DEPOSIT_FAILURE = "GET_PAYMENT_DEPOSIT_FAILURE";

// Get data of selected model
export const SET_PAYMENT_DEPOSIT = "SET_PAYMENT_DEPOSIT";
export const SET_PAYMENT_DEPOSIT_SUCCESS = "SET_PAYMENT_DEPOSIT_SUCCESS";
export const SET_PAYMENT_DEPOSIT_FAILURE = "SET_PAYMENT_DEPOSIT_FAILURE";


// GET FILTERS
export const GET_FILTER_PAYMENT_DEPOSIT = "GET_FILTER_PAYMENT_DEPOSIT";
export const GET_FILTER_PAYMENT_DEPOSIT_SUCCESS = "GET_FILTER_PAYMENT_DEPOSIT_SUCCESS";
export const GET_FILTER_PAYMENT_DEPOSIT_FAILURE = "GET_FILTER_PAYMENT_DEPOSIT_FAILURE";

// DELETE PAYMENT_DEPOSIT
export const DELETE_PAYMENT_DEPOSIT = "DELETE_PAYMENT_DEPOSIT";
export const DELETE_PAYMENT_DEPOSIT_SUCCESS = "DELETE_PAYMENT_DEPOSIT_SUCCESS";
export const DELETE_PAYMENT_DEPOSIT_FAILURE = "DELETE_PAYMENT_DEPOSIT_FAILURE";


//get single invoice
export const GET_SINGLE_PAYMENT_DEPOSIT_REQUEST = "GET_SINGLE_PAYMENT_DEPOSIT_REQUEST";
export const GET_SINGLE_PAYMENT_DEPOSIT_REQUEST_SUCCESS = "GET_SINGLE_PAYMENT_DEPOSIT_REQUEST_SUCCESS";
export const GET_SINGLE_PAYMENT_DEPOSIT_REQUEST_FAILURE = "GET_SINGLE_PAYMENT_DEPOSIT_REQUEST_FAILURE";

//patch single invoice
export const PATCH_SINGLE_PAYMENT_DEPOSIT = "PATCH_SINGLE_PAYMENT_DEPOSIT";
export const PATCH_SINGLE_PAYMENT_DEPOSIT_SUCCESS = "PATCH_SINGLE_PAYMENT_DEPOSIT_SUCCESS";
export const PATCH_SINGLE_PAYMENT_DEPOSIT_FAILURE = "PATCH_SINGLE_PAYMENT_DEPOSIT_FAILURE";

// get pdf
export const GET_PAYMENT_DEPOSIT_PDF = "GET_PAYMENT_DEPOSIT_PDF";
export const GET_PAYMENT_DEPOSIT_PDF_SUCCESS = "GET_PAYMENT_DEPOSIT_PDF_SUCCESS";
export const GET_PAYMENT_DEPOSIT_PDF_FAILURE = "GET_PAYMENT_DEPOSIT_PDF_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_DEPOSIT_QUERY = 'GET_SAVED_DEPOSIT_QUERY';
export const GET_SAVED_DEPOSIT_QUERY_SUCCESS = 'GET_SAVED_DEPOSIT_QUERY_SUCCESS';
export const GET_SAVED_DEPOSIT_QUERY_FAILURE = 'GET_SAVED_DEPOSIT_QUERY_FAILURE';

