// Get data of selected model
export const GET_SALES_ORDER = "GET_SALES_ORDER";
export const GET_SALES_ORDER_SUCCESS = "GET_SALES_ORDER_SUCCESS";
export const GET_SALES_ORDER_FAILURE = "GET_SALES_ORDER_FAILURE";

// Get data of selected model
export const SET_SALES_ORDER = "SET_SALES_ORDER";
export const SET_SALES_ORDER_SUCCESS = "SET_SALES_ORDER_SUCCESS";
export const SET_SALES_ORDER_FAILURE = "SET_SALES_ORDER_FAILURE";

// GET DETAILS
export const GET_SALES_ORDER_DETAILS = "GET_SALES_ORDER_DETAILS";
export const GET_SALES_ORDER_DETAILS_SUCCESS = "GET_SALES_ORDER_DETAILS_SUCCESS";
export const GET_SALES_ORDER_DETAILS_FAILURE = "GET_SALES_ORDER_DETAILS_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";

// SET NEW VERSION
export const SET_NEW_VERSION_SALESORDER_REQUEST = 'SET_NEW_VERSION_SALESORDER_REQUEST'
export const SET_NEW_VERSION_SALESORDER_SUCCESS = 'SET_NEW_VERSION_SALESORDER_SUCCESS'
export const SET_NEW_VERSION_SALESORDER_FAILURE = 'SET_NEW_VERSION_SALESORDER_FAILURE'

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

// GET FILTERED DEETS
export const GET_FILTER_SALES_ORDER = "GET_FILTER_SALES_ORDER";
export const GET_FILTER_SALES_ORDER_SUCCESS = "GET_FILTER_SALES_ORDER_SUCCESS";
export const GET_FILTER_SALES_ORDER_FAILURE = "GET_FILTER_SALES_ORDER_FAILURE";

// DAVID- RESET FILTER_SALES_ORDER & SINGLE SKU RESET
export const GET_FILTER_SALES_ORDER_AND_SINGLE_SKU_RESET =
  "GET_FILTER_SALES_ORDER_AND_SINGLE_SKU_RESET";

// David - GET - SKUSALES_ORDERbyID
export const GET_SINGLE_SKU_SALES_ORDER_REQUEST = "GET_SINGLE_SKU_SALES_ORDER_REQUEST";
export const GET_SINGLE_SKU_SALES_ORDER_SUCCESS = "GET_SINGLE_SKU_SALES_ORDER_SUCCESS";
export const GET_SINGLE_SKU_SALES_ORDER_FAILURE = "GET_SINGLE_SKU_SALES_ORDER_FAILURE";

// David - PATCH- SKUSALES_ORDERbyID | Update
export const PATCH_SINGLE_SKU_SALES_ORDER_REQUEST =
  "PATCH_SINGLE_SKU_SALES_ORDER_REQUEST";
export const PATCH_SINGLE_SKU_SALES_ORDER_SUCCESS =
  "PATCH_SINGLE_SKU_SALES_ORDER_SUCCESS";
export const PATCH_SINGLE_SKU_SALES_ORDER_FAILURE =
  "PATCH_SINGLE_SKU_SALES_ORDER_FAILURE";

// DELETE SKU DETAILS
export const DELETE_SALES_ORDER = "DELETE_SALES_ORDER";
export const DELETE_SALES_ORDER_SUCCESS = "DELETE_SALES_ORDER_SUCCESS";
export const DELETE_SALES_ORDER_FAILURE = "DELETE_SALES_ORDER_FAILURE";


// CONVERT TO SALES ORDER
export const CONVERT_TO_SALES_ORDER_REQUEST = "CONVERT_TO_SALES_ORDER_REQUEST";
export const CONVERT_TO_SALES_ORDER_SUCCESS = "CONVERT_TO_SALES_ORDER_SUCCESS";
export const CONVERT_TO_SALES_ORDER_FAILURE = "CONVERT_TO_SALES_ORDER_FAILURE";


//PDF CREATE
export const PDF_CREATE_SALES_ORDER = 'PDF_CREATE_SALES_ORDER'
export const PDF_CREATE_SALES_ORDER_SUCCESS = 'PDF_CREATE_SALES_ORDER_SUCCESS'
export const PDF_CREATE_SALES_ORDER_FAILURE = 'PDF_CREATE_SALES_ORDER_FAILURE'

// patch internal remarks for single sales on dashboard 
export const PATCH_SINGLE_SALES_REQUEST_INTERNAL_REMARKS = "PATCH_SINGLE_SALES_REQUEST_INTERNAL_REMARKS";
export const PATCH_SINGLE_SALES_REQUEST_INTERNAL_REMARKS_SUCCESS = "PATCH_SINGLE_SALES_INTERNAL_REMARKS_SUCCESS";
export const PATCH_SINGLE_SALES_REQUEST_INTERNAL_REMARKS_FAILURE = "PATCH_SINGLE_SALES_INTERNAL_REMARKS_FAILURE";

//SAVE QUERIES FOR COMMERCIAL SALES ORDER
export const GET_SAVED_SALES_QUERY = 'GET_SAVED_SALES_QUERY';
export const GET_SAVED_SALES_QUERY_SUCCESS = 'GET_SAVED_SALES_QUERY_SUCCESS';
export const GET_SAVED_SALES_QUERY_FAILURE = 'GET_SAVED_SALES_QUERY_FAILURE';

//SAVE QUERIES FOR ACCOUNTING SALES ORDER
export const GET_SAVED_ACCT_SALES_QUERY = 'GET_SAVED_ACCT_SALES_QUERY';
export const GET_SAVED_ACCT_SALES_QUERY_SUCCESS = 'GET_SAVED_ACCT_SALES_QUERY_SUCCESS';
export const GET_SAVED_ACCT_SALES_QUERY_FAILURE = 'GET_SAVED_ACCT_SALES_QUERY_FAILURE';

//GET PURCHASE TEMP LIST 
export const GET_PURCHASE_TEMP_LIST = 'GET_PURCHASE_TEMP_LIST';
export const GET_PURCHASE_TEMP_LIST_SUCCESS = 'GET_PURCHASE_TEMP_LIST_SUCCESS';
export const GET_PURCHASE_TEMP_LIST_FAILURE = 'GET_PURCHASE_TEMP_LIST_FAILURE';

// POST PURCHASE TEMP LIST 
export const POST_PURCHASE_TEMP_LIST = "POST_PURCHASE_TEMP_LIST";
export const POST_PURCHASE_TEMP_LIST_SUCCESS = "POST_PURCHASE_TEMP_LIST_SUCCESS";
export const POST_PURCHASE_TEMP_LIST_FAILURE = "POST_PURCHASE_TEMP_LIST_FAILURE";

// INVOICE PDF CREATE
export const GET_SALESORDER_PROFORMA_INVOICE_PDF = "GET_SALESORDER_PROFORMA_INVOICE_PDF";
export const GET_SALESORDER_PROFORMA_INVOICE_PDF_SUCCESS = "GET_SALESORDER_PROFORMA_INVOICE_PDF_SUCCESS";
export const GET_SALESORDER_PROFORMA_INVOICE_PDF_FAILURE = "GET_SALESORDER_PROFORMA_INVOICE_PDF_FAILURE";
// INVOICE PDF CREATE
export const GET_SALESORDER_COMMERCIAL_INVOICE_PDF = "GET_SALESORDER_COMMERCIAL_INVOICE_PDF";
export const GET_SALESORDER_COMMERCIAL_INVOICE_PDF_SUCCESS = "GET_SALESORDER_COMMERCIAL_INVOICE_PDF_SUCCESS";
export const GET_SALESORDER_COMMERCIAL_INVOICE_PDF_FAILURE = "GET_SALESORDER_COMMERCIAL_INVOICE_PDF_FAILURE";
