// GET all CAPEXs
export const GET_ALL_CAPEXS = "GET_ALL_CAPEXS";
export const GET_ALL_CAPEXS_SUCCESS = "GET_ALL_CAPEXS_SUCCESS";
export const GET_ALL_CAPEXS_FAILURE = "GET_ALL_CAPEXS_FAILURE";

// GET one CAPEX
export const GET_CAPEX = "GET_CAPEX";
export const GET_CAPEX_SUCCESS = "GET_CAPEX_SUCCESS";
export const GET_CAPEX_FAILURE = "GET_CAPEX_FAILURE";

// POST one CAPEX 
export const POST_CAPEX = "POST_CAPEX";
export const POST_CAPEX_SUCCESS = "POST_CAPEX_SUCCESS";
export const POST_CAPEX_FAILURE = "POST_CAPEX_FAILURE";

// PATCH one CAPEX 
export const PATCH_CAPEX = "PATCH_CAPEX";
export const PATCH_CAPEX_SUCCESS = "PATCH_CAPEX_SUCCESS";
export const PATCH_CAPEX_FAILURE = "PATCH_CAPEX_FAILURE";

// DELETE one CAPEX  
export const DELETE_CAPEX = "DELETE_CAPEX";
export const DELETE_CAPEX_SUCCESS = "DELETE_CAPEX_SUCCESS";
export const DELETE_CAPEX_FAILURE = "DELETE_CAPEX_FAILURE";
