// GET all stock locations
export const GET_ALL_STOCK_LOCATIONS = "GET_ALL_STOCK_LOCATIONS";
export const GET_ALL_STOCK_LOCATIONS_SUCCESS = "GET_ALL_STOCK_LOCATIONS_SUCCESS";
export const GET_ALL_STOCK_LOCATIONS_FAILURE = "GET_ALL_STOCK_LOCATIONS_FAILURE";

// GET one stock location
export const GET_STOCK_LOCATION = "GET_STOCK_LOCATION";
export const GET_STOCK_LOCATION_SUCCESS = "GET_STOCK_LOCATION_SUCCESS";
export const GET_STOCK_LOCATION_FAILURE = "GET_STOCK_LOCATION_FAILURE";

// POST one stock location 
export const POST_STOCK_LOCATION = "POST_STOCK_LOCATION";
export const POST_STOCK_LOCATION_SUCCESS = "POST_STOCK_LOCATION_SUCCESS";
export const POST_STOCK_LOCATION_FAILURE = "POST_STOCK_LOCATION_FAILURE";

// PATCH one stock location 
export const PATCH_STOCK_LOCATION = "PATCH_STOCK_LOCATION";
export const PATCH_STOCK_LOCATION_SUCCESS = "PATCH_STOCK_LOCATION_SUCCESS";
export const PATCH_STOCK_LOCATION_FAILURE = "PATCH_STOCK_LOCATION_FAILURE";

// DELETE one stock location  
export const DELETE_STOCK_LOCATION = "DELETE_STOCK_LOCATION";
export const DELETE_STOCK_LOCATION_SUCCESS = "DELETE_STOCK_LOCATION_SUCCESS";
export const DELETE_STOCK_LOCATION_FAILURE = "DELETE_STOCK_LOCATION_FAILURE";
