// Get data of selected model
export const GET_CUSTOMERTFES = "GET_CUSTOMERTFES";
export const GET_CUSTOMERTFES_SUCCESS = "GET_CUSTOMERTFES_SUCCESS";
export const GET_CUSTOMERTFES_FAILURE = "GET_CUSTOMERTFES_FAILURE";

// Get data of selected model
export const SET_CUSTOMERTFES = "SET_CUSTOMERTFES";
export const SET_CUSTOMERTFES_SUCCESS = "SET_CUSTOMERTFES_SUCCESS";
export const SET_CUSTOMERTFES_FAILURE = "SET_CUSTOMERTFES_FAILURE";

// GET DETAILS
export const GET_CUSTOMERTFES_DETAILS = "GET_CUSTOMERTFES_DETAILS";
export const GET_CUSTOMERTFES_DETAILS_SUCCESS =
  "GET_CUSTOMERTFES_DETAILS_SUCCESS";
export const GET_CUSTOMERTFES_DETAILS_FAILURE =
  "GET_CUSTOMERTFES_DETAILS_FAILURE";

// GET FILTERED DEETS
export const GET_FILTER_CUSTOMERTFES = "GET_FILTER_CUSTOMERTFES";
export const GET_FILTER_CUSTOMERTFES_SUCCESS =
  "GET_FILTER_CUSTOMERTFES_SUCCESS";
export const GET_FILTER_CUSTOMERTFES_FAILURE =
  "GET_FILTER_CUSTOMERTFES_FAILURE";

// DELETE SKU DETAILS
export const DELETE_CUSTOMERTFES = "DELETE_CUSTOMERTFES";
export const DELETE_CUSTOMERTFES_SUCCESS = "DELETE_CUSTOMERTFES_SUCCESS";
export const DELETE_CUSTOMERTFES_FAILURE = "DELETE_CUSTOMERTFES_FAILURE";

// David - GET - SINGLE CUSTOMER BY ID
export const GET_SINGLE_CUSTOMER_REQUEST = "GET_SINGLE_CUSTOMER_REQUEST";
export const GET_SINGLE_CUSTOMER_SUCCESS = "GET_SINGLE_CUSTOMER_SUCCESS";
export const GET_SINGLE_CUSTOMER_FAILURE = "GET_SINGLE_CUSTOMER_FAILURE";

// David - Patch - SINGLE CUSTOMER BY ID
export const PATCH_SINGLE_CUSTOMER_REQUEST = "PATCH_SINGLE_CUSTOMER_REQUEST";
export const PATCH_SINGLE_CUSTOMER_SUCCESS = "PATCH_SINGLE_CUSTOMER_SUCCESS";
export const PATCH_SINGLE_CUSTOMER_FAILURE = "PATCH_SINGLE_CUSTOMER_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_CUSTOMER_QUERY = 'GET_SAVED_CUSTOMER_QUERY';
export const GET_SAVED_CUSTOMER_QUERY_SUCCESS = 'GET_SAVED_CUSTOMER_QUERY_SUCCESS';
export const GET_SAVED_CUSTOMER_QUERY_FAILURE = 'GET_SAVED_CUSTOMER_QUERY_FAILURE';

