// GET ALL CLAIMS
export const GET_ALL_EXPENSE_CLAIMS = "GET_ALL_EXPENSE_CLAIMS";
export const GET_ALL_EXPENSE_CLAIMS_SUCCESS = "GET_ALL_EXPENSE_CLAIMS_SUCCESS";
export const GET_ALL_EXPENSE_CLAIMS_FAILURE = "GET_ALL_EXPENSE_CLAIMS_FAILURE";

// GET ALL FILTER CLAIMS
export const GET_ALL_FILTER_EXPENSE_CLAIMS = "GET_ALL_FILTER_EXPENSE_CLAIMS";
export const GET_ALL_FILTER_EXPENSE_CLAIMS_SUCCESS = "GET_ALL_FILTER_EXPENSE_CLAIMS_SUCCESS";
export const GET_ALL_FILTER_EXPENSE_CLAIMS_FAILURE = "GET_ALL_FILTER_EXPENSE_CLAIMS_FAILURE";

// GET CLAIMS 
export const GET_EXPENSE_CLAIMS = "GET_EXPENSE_CLAIMS";
export const GET_EXPENSE_CLAIMS_SUCCESS = "GET_EXPENSE_CLAIMS_SUCCESS";
export const GET_EXPENSE_CLAIMS_FAILURE = "GET_EXPENSE_CLAIMS_FAILURE";

//POST CLAIMS 
export const POST_EXPENSE_CLAIMS = "POST_EXPENSE_CLAIMS";
export const POST_EXPENSE_CLAIMS_SUCCESS = "POST_EXPENSE_CLAIMS_SUCCESS";
export const POST_EXPENSE_CLAIMS_FAILURE = "POST_EXPENSE_CLAIMS_FAILURE";

//UPDATE CLAIMS 
export const PATCH_EXPENSE_CLAIMS = "PATCH_EXPENSE_CLAIMS";
export const PATCH_EXPENSE_CLAIMS_SUCCESS = "PATCH_EXPENSE_CLAIMS_SUCCESS";
export const PATCH_EXPENSE_CLAIMS_FAILURE = "PATCH_EXPENSE_CLAIMS_FAILURE";

//DELETE CLAIMS 
export const DELETE_EXPENSE_CLAIMS = "DELETE_EXPENSE_CLAIMS";
export const DELETE_EXPENSE_CLAIMS_SUCCESS = "DELETE_EXPENSE_CLAIMS_SUCCESS";
export const DELETE_EXPENSE_CLAIMS_FAILURE = "DELETE_EXPENSE_CLAIMS_FAILURE";