// GET all CREDIT_TERMs
export const GET_ALL_CREDIT_TERMS = "GET_ALL_CREDIT_TERMS";
export const GET_ALL_CREDIT_TERMS_SUCCESS = "GET_ALL_CREDIT_TERMS_SUCCESS";
export const GET_ALL_CREDIT_TERMS_FAILURE = "GET_ALL_CREDIT_TERMS_FAILURE";

// GET one CREDIT_TERM
export const GET_CREDIT_TERM = "GET_CREDIT_TERM";
export const GET_CREDIT_TERM_SUCCESS = "GET_CREDIT_TERM_SUCCESS";
export const GET_CREDIT_TERM_FAILURE = "GET_CREDIT_TERM_FAILURE";

// POST one CREDIT_TERM 
export const POST_CREDIT_TERM = "POST_CREDIT_TERM";
export const POST_CREDIT_TERM_SUCCESS = "POST_CREDIT_TERM_SUCCESS";
export const POST_CREDIT_TERM_FAILURE = "POST_CREDIT_TERM_FAILURE";

// PATCH one CREDIT_TERM 
export const PATCH_CREDIT_TERM = "PATCH_CREDIT_TERM";
export const PATCH_CREDIT_TERM_SUCCESS = "PATCH_CREDIT_TERM_SUCCESS";
export const PATCH_CREDIT_TERM_FAILURE = "PATCH_CREDIT_TERM_FAILURE";

// DELETE one CREDIT_TERM  
export const DELETE_CREDIT_TERM = "DELETE_CREDIT_TERM";
export const DELETE_CREDIT_TERM_SUCCESS = "DELETE_CREDIT_TERM_SUCCESS";
export const DELETE_CREDIT_TERM_FAILURE = "DELETE_CREDIT_TERM_FAILURE";
