// GET all STOCK EXPENSE  
export const GET_ALL_STOCK_EXPENSE = "GET_ALL_STOCK_EXPENSE";
export const GET_ALL_STOCK_EXPENSE_SUCCESS = "GET_ALL_STOCK_EXPENSE_SUCCESS";
export const GET_ALL_STOCK_EXPENSE_FAILURE = "GET_ALL_STOCK_EXPENSE_FAILURE";

// GET one STOCK EXPENSE  
export const GET_STOCK_EXPENSE = "GET_STOCK_EXPENSE";
export const GET_STOCK_EXPENSE_SUCCESS = "GET_STOCK_EXPENSE_SUCCESS";
export const GET_STOCK_EXPENSE_FAILURE = "GET_STOCK_EXPENSE_FAILURE";

// POST one STOCK EXPENSE   
export const POST_STOCK_EXPENSE = "POST_STOCK_EXPENSE";
export const POST_STOCK_EXPENSE_SUCCESS = "POST_STOCK_EXPENSE_SUCCESS";
export const POST_STOCK_EXPENSE_FAILURE = "POST_STOCK_EXPENSE_FAILURE";

// PATCH one STOCK EXPENSE   
export const PATCH_STOCK_EXPENSE = "PATCH_STOCK_EXPENSE";
export const PATCH_STOCK_EXPENSE_SUCCESS = "PATCH_STOCK_EXPENSE_SUCCESS";
export const PATCH_STOCK_EXPENSE_FAILURE = "PATCH_STOCK_EXPENSE_FAILURE";

// DELETE one STOCK EXPENSE  
export const DELETE_STOCK_EXPENSE = "DELETE_STOCK_EXPENSE";
export const DELETE_STOCK_EXPENSE_SUCCESS = "DELETE_STOCK_EXPENSE_SUCCESS";
export const DELETE_STOCK_EXPENSE_FAILURE = "DELETE_STOCK_EXPENSE_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_STOCK_EXPENSE_QUERY = 'GET_SAVED_STOCK_EXPENSE_QUERY';
export const GET_SAVED_STOCK_EXPENSE_QUERY_SUCCESS = 'GET_SAVED_STOCK_EXPENSE_QUERY_SUCCESS';
export const GET_SAVED_STOCK_EXPENSE_QUERY_FAILURE = 'GET_SAVED_STOCK_EXPENSE_QUERY_FAILURE';
