// GET all stock locations
export const GET_ALL_INCO_TERMS = "GET_ALL_INCO_TERMS";
export const GET_ALL_INCO_TERMS_SUCCESS = "GET_ALL_INCO_TERMS_SUCCESS";
export const GET_ALL_INCO_TERMS_FAILURE = "GET_ALL_INCO_TERMS_FAILURE";

// GET one stock location
export const GET_INCO_TERM = "GET_INCO_TERM";
export const GET_INCO_TERM_SUCCESS = "GET_INCO_TERM_SUCCESS";
export const GET_INCO_TERM_FAILURE = "GET_INCO_TERM_FAILURE";

// POST one stock location 
export const POST_INCO_TERM = "POST_INCO_TERM";
export const POST_INCO_TERM_SUCCESS = "POST_INCO_TERM_SUCCESS";
export const POST_INCO_TERM_FAILURE = "POST_INCO_TERM_FAILURE";

// PATCH one stock location 
export const PATCH_INCO_TERM = "PATCH_INCO_TERM";
export const PATCH_INCO_TERM_SUCCESS = "PATCH_INCO_TERM_SUCCESS";
export const PATCH_INCO_TERM_FAILURE = "PATCH_INCO_TERM_FAILURE";

// DELETE one stock location  
export const DELETE_INCO_TERM = "DELETE_INCO_TERM";
export const DELETE_INCO_TERM_SUCCESS = "DELETE_INCO_TERM_SUCCESS";
export const DELETE_INCO_TERM_FAILURE = "DELETE_INCO_TERM_FAILURE";
