// Get data of selected model
export const GET_INVOICE = "GET_INVOICE";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_INVOICE_FAILURE = "GET_INVOICE_FAILURE";

// Get data of selected model
export const SET_INVOICE = "SET_INVOICE";
export const SET_INVOICE_SUCCESS = "SET_INVOICE_SUCCESS";
export const SET_INVOICE_FAILURE = "SET_INVOICE_FAILURE";

// GET DETAILS
export const GET_DROPDOWN_GROUP = "GET_DROPDOWN_GROUP";
export const GET_DROPDOWN_GROUP_SUCCESS = "GET_DROPDOWN_GROUP_SUCCESS";
export const GET_DROPDOWN_GROUP_FAILURE = "GET_DROPDOWN_GROUP_FAILURE";

// GET FILTERS
export const GET_FILTER_INVOICE = "GET_FILTER_INVOICE";
export const GET_FILTER_INVOICE_SUCCESS = "GET_FILTER_INVOICE_SUCCESS";
export const GET_FILTER_INVOICE_FAILURE = "GET_FILTER_INVOICE_FAILURE";

// DELETE INVOICE
export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAILURE = "DELETE_INVOICE_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

//get single invoice
export const GET_SINGLE_INVOICE_REQUEST = "GET_SINGLE_INVOICE_REQUEST";
export const GET_SINGLE_INVOICE_REQUEST_SUCCESS = "GET_SINGLE_INVOICE_REQUEST_SUCCESS";
export const GET_SINGLE_INVOICE_REQUEST_FAILURE = "GET_SINGLE_INVOICE_REQUEST_FAILURE";

//patch single invoice
export const PATCH_SINGLE_INVOICE = "PATCH_SINGLE_INVOICE";
export const PATCH_SINGLE_INVOICE_SUCCESS = "PATCH_SINGLE_INVOICE_SUCCESS";
export const PATCH_SINGLE_INVOICE_FAILURE = "PATCH_SINGLE_INVOICE_FAILURE";


export const GET_TAX_INVOICE_PDF = "GET_TAX_INVOICE_PDF";
export const GET_TAX_INVOICE_PDF_SUCCESS = "GET_TAX_INVOICE_PDF_SUCCESS";
export const GET_TAX_INVOICE_PDF_FAILURE = "GET_TAX_INVOICE_PDF_FAILURE";

export const GET_PROFORMA_INVOICE_PDF = "GET_PROFORMA_INVOICE_PDF";
export const GET_PROFORMA_INVOICE_PDF_SUCCESS = "GET_PROFORMA_INVOICE_PDF_SUCCESS";
export const GET_PROFORMA_INVOICE_PDF_FAILURE = "GET_PROFORMA_INVOICE_PDF_FAILURE";

export const GET_COMMERCIAL_INVOICE_PDF = "GET_COMMERCIAL_INVOICE_PDF";
export const GET_COMMERCIAL_INVOICE_PDF_SUCCESS = "GET_COMMERCIAL_INVOICE_PDF_SUCCESS";
export const GET_COMMERCIAL_INVOICE_PDF_FAILURE = "GET_COMMERCIAL_INVOICE_PDF_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_INVOICE_QUERY = 'GET_SAVED_INVOICE_QUERY';
export const GET_SAVED_INVOICE_QUERY_SUCCESS = 'GET_SAVED_INVOICE_QUERY_SUCCESS';
export const GET_SAVED_INVOICE_QUERY_FAILURE = 'GET_SAVED_INVOICE_QUERY_FAILURE';