// GET all LEAVE_MANAGEMENT
export const GET_ALL_LEAVE_MANAGEMENT = "GET_ALL_LEAVE_MANAGEMENT";
export const GET_ALL_LEAVE_MANAGEMENT_SUCCESS = "GET_ALL_LEAVE_MANAGEMENT_SUCCESS";
export const GET_ALL_LEAVE_MANAGEMENT_FAILURE = "GET_ALL_LEAVE_MANAGEMENT_FAILURE";

// GET one LEAVE_MANAGEMENT
export const GET_LEAVE_MANAGEMENT = "GET_LEAVE_MANAGEMENT";
export const GET_LEAVE_MANAGEMENT_SUCCESS = "GET_LEAVE_MANAGEMENT_SUCCESS";
export const GET_LEAVE_MANAGEMENT_FAILURE = "GET_LEAVE_MANAGEMENT_FAILURE";

// POST one LEAVE_MANAGEMENT 
export const POST_LEAVE_MANAGEMENT = "POST_LEAVE_MANAGEMENT";
export const POST_LEAVE_MANAGEMENT_SUCCESS = "POST_LEAVE_MANAGEMENT_SUCCESS";
export const POST_LEAVE_MANAGEMENT_FAILURE = "POST_LEAVE_MANAGEMENT_FAILURE";

// PATCH one LEAVE_MANAGEMENT 
export const PATCH_LEAVE_MANAGEMENT = "PATCH_LEAVE_MANAGEMENT";
export const PATCH_LEAVE_MANAGEMENT_SUCCESS = "PATCH_LEAVE_MANAGEMENT_SUCCESS";
export const PATCH_LEAVE_MANAGEMENT_FAILURE = "PATCH_LEAVE_MANAGEMENT_FAILURE";

// DELETE one LEAVE_MANAGEMENT  
export const DELETE_LEAVE_MANAGEMENT = "DELETE_LEAVE_MANAGEMENT";
export const DELETE_LEAVE_MANAGEMENT_SUCCESS = "DELETE_LEAVE_MANAGEMENT_SUCCESS";
export const DELETE_LEAVE_MANAGEMENT_FAILURE = "DELETE_LEAVE_MANAGEMENT_FAILURE";

//Filter
export const GET_FILTER_LEAVE_MANAGEMENT = "GET_FILTER_LEAVE_MANAGEMENT";
export const GET_FILTER_LEAVE_MANAGEMENT_SUCCESS = "GET_FILTER_LEAVE_MANAGEMENT_SUCCESS";
export const GET_FILTER_LEAVE_MANAGEMENT_FAILURE = "GET_FILTER_LEAVE_MANAGEMENT_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";