// Get data of selected model
export const GET_SUPPLIER = "GET_SUPPLIER";
export const GET_SUPPLIER_SUCCESS = "GET_SUPPLIER_SUCCESS";
export const GET_SUPPLIER_FAILURE = "GET_SUPPLIER_FAILURE";

// Get data of selected model
export const SET_SUPPLIER = "SET_SUPPLIER";
export const SET_SUPPLIER_SUCCESS = "SET_SUPPLIER_SUCCESS";
export const SET_SUPPLIER_FAILURE = "SET_SUPPLIER_FAILURE";

// GET DETAILS
export const GET_SUPPLIER_DETAILS = "GET_SUPPLIER_DETAILS";
export const GET_SUPPLIER_DETAILS_SUCCESS = "GET_SUPPLIER_DETAILS_SUCCESS";
export const GET_SUPPLIER_DETAILS_FAILURE = "GET_SUPPLIER_DETAILS_FAILURE";

// GET FILTERED DEETS
export const GET_FILTER_SUPPLIER = "GET_FILTER_SUPPLIER";
export const GET_FILTER_SUPPLIER_SUCCESS = "GET_FILTER_SUPPLIER_SUCCESS";
export const GET_FILTER_SUPPLIER_FAILURE = "GET_FILTER_SUPPLIER_FAILURE";

// DELETE SKU DETAILS
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const DELETE_SUPPLIER_SUCCESS = "DELETE_SUPPLIER_SUCCESS";
export const DELETE_SUPPLIER_FAILURE = "DELETE_SUPPLIER_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";
// David - GET - SINGLE SUPPLIER BY ID
export const GET_SINGLE_SUPPLIER_REQUEST = "GET_SINGLE_SUPPLIER_REQUEST";
export const GET_SINGLE_SUPPLIER_SUCCESS = "GET_SINGLE_SUPPLIER_SUCCESS";
export const GET_SINGLE_SUPPLIER_FAILURE = "GET_SINGLE_SUPPLIER_FAILURE";

// David - PATCH - SINGLE SUPPLIER BY ID
export const PATCH_SINGLE_SUPPLIER_REQUEST = "PATCH_SINGLE_SUPPLIER_REQUEST";
export const PATCH_SINGLE_SUPPLIER_SUCCESS = "PATCH_SINGLE_SUPPLIER_SUCCESS";
export const PATCH_SINGLE_SUPPLIER_FAILURE = "PATCH_SINGLE_SUPPLIER_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_SUPPLIER_MAIN_QUERY = 'GET_SAVED_SUPPLIER_MAIN_QUERY';
export const GET_SAVED_SUPPLIER_MAIN_QUERY_SUCCESS = 'GET_SAVED_SUPPLIER_MAIN_QUERY_SUCCESS';
export const GET_SAVED_SUPPLIER_MAIN_QUERY_FAILURE = 'GET_SAVED_SUPPLIER_MAIN_QUERY_FAILURE';
