// GET all PAYMENT TERMs
export const GET_ALL_PURCHASE_SETTINGS = "GET_ALL_PURCHASE_SETTINGS";
export const GET_ALL_PURCHASE_SETTINGS_SUCCESS = "GET_ALL_PURCHASE_SETTINGS_SUCCESS";
export const GET_ALL_PURCHASE_SETTINGS_FAILURE = "GET_ALL_PURCHASE_SETTINGS_FAILURE";

// GET one PAYMENT TERM
export const GET_PURCHASE_SETTING = "GET_PURCHASE_SETTING";
export const GET_PURCHASE_SETTING_SUCCESS = "GET_PURCHASE_SETTING_SUCCESS";
export const GET_PURCHASE_SETTING_FAILURE = "GET_PURCHASE_SETTING_FAILURE";

// POST one PAYMENT TERM 
export const POST_PURCHASE_SETTING = "POST_PURCHASE_SETTING";
export const POST_PURCHASE_SETTING_SUCCESS = "POST_PURCHASE_SETTING_SUCCESS";
export const POST_PURCHASE_SETTING_FAILURE = "POST_PURCHASE_SETTING_FAILURE";

// PATCH one PAYMENT TERM 
export const PATCH_PURCHASE_SETTING = "PATCH_PURCHASE_SETTING";
export const PATCH_PURCHASE_SETTING_SUCCESS = "PATCH_PURCHASE_SETTING_SUCCESS";
export const PATCH_PURCHASE_SETTING_FAILURE = "PATCH_PURCHASE_SETTING_FAILURE";

// DELETE one PAYMENT TERM  
export const DELETE_PURCHASE_SETTING = "DELETE_PURCHASE_SETTING";
export const DELETE_PURCHASE_SETTING_SUCCESS = "DELETE_PURCHASE_SETTING_SUCCESS";
export const DELETE_PURCHASE_SETTING_FAILURE = "DELETE_PURCHASE_SETTING_FAILURE";
