export const GET_ALL_PACKING = "GET_ALL_PACKING";
export const GET_ALL_PACKING_FAILURE = "GET_ALL_PACKING_FAILURE";
export const GET_ALL_PACKING_SUCCESS = "GET_ALL_PACKING_SUCCESS";

export const GET_FILTER_PACKING = "GET_FILTER_PACKING";
export const GET_FILTER_PACKING_FAILURE = "GET_FILTER_PACKING_FAILURE";
export const GET_FILTER_PACKING_SUCCESS = "GET_FILTER_PACKING_SUCCESS";

export const GET_PACKING_MOVE_LINE = "GET_PACKING_MOVE_LINE";
export const GET_PACKING_MOVE_LINE_FAILURE = "GET_PACKING_MOVE_LINE_FAILURE";
export const GET_PACKING_MOVE_LINE_SUCCESS = "GET_PACKING_MOVE_LINE_SUCCESS";

export const SAVE_PACKING_FORM = "SAVE_PACKING_FORM";
export const SAVE_PACKING_FORM_FAILURE = "SAVE_PACKING_FORM_FAILURE";
export const SAVE_PACKING_FORM_SUCCESS = "SAVE_PACKING_FORM_SUCCESS";

export const GET_FILTER_MOVES = "GET_FILTER_MOVES";
export const GET_FILTER_MOVES_FAILURE = "GET_FILTER_MOVES_FAILURE";
export const GET_FILTER_MOVES_SUCCESS = "GET_FILTER_MOVES_SUCCESS";

export const PATCH_SINGLE_SKU_PACKING_ORDER_REQUEST =
  "PATCH_SINGLE_SKU_PACKING_ORDER_REQUEST";
export const PATCH_SINGLE_SKU_PACKING_ORDER_SUCCESS =
  "PATCH_SINGLE_SKU_PACKING_ORDER_SUCCESS";
export const PATCH_SINGLE_SKU_PACKING_ORDER_FAILURE =
  "PATCH_SINGLE_SKU_PACKING_ORDER_FAILURE";

export const PATCH_SINGLE_QTY_PACKING =
  "PATCH_SINGLE_QTY_PACKING";
export const PATCH_SINGLE_QTY_PACKING_SUCCESS =
  "PATCH_SINGLE_QTY_PACKING_SUCCESS";
export const PATCH_SINGLE_QTY_PACKING_FAILURE =
  "PATCH_SINGLE_QTY_PACKING_FAILURE";

export const PATCH_CONTAINER_PACKING_ORDER = "PATCH_CONTAINER_PACKING_ORDER";
export const PATCH_CONTAINER_PACKING_ORDER_SUCCESS = "PATCH_CONTAINER_PACKING_ORDER_SUCCESS";
export const PATCH_CONTAINER_PACKING_ORDER_FAILURE = "PATCH_CONTAINER_PACKING_ORDER_FAILURE";

export const DELETE_PACKING_ORDER = "DELETE_PACKING_ORDER";
export const DELETE_PACKING_ORDER_SUCCESS = "DELETE_PACKING_ORDER_SUCCESS";
export const DELETE_PACKING_ORDER_FAILURE = "DELETE_PACKING_ORDER_FAILURE";

//PDF CREATE
export const PDF_CREATE_PACKING_ORDER = 'PDF_CREATE_PACKING_ORDER'
export const PDF_CREATE_PACKING_ORDER_SUCCESS = 'PDF_CREATE_PACKING_ORDER_SUCCESS'
export const PDF_CREATE_PACKING_ORDER_FAILURE = 'PDF_CREATE_PACKING_ORDER_FAILURE'

//PDF COMMERCIAL INVOICE CREATE
export const GET_CREATE_COMMERCIAL_INVOICE_PDF = "GET_CREATE_COMMERCIAL_INVOICE_PDF";
export const GET_CREATE_COMMERCIAL_INVOICE_PDF_SUCCESS = "GET_CREATE_COMMERCIAL_INVOICE_PDF_SUCCESS";
export const GET_CREATE_COMMERCIAL_INVOICE_PDF_FAILURE = "GET_CREATE_COMMERCIAL_INVOICE_PDF_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_PACKING_QUERY = 'GET_SAVED_PACKING_QUERY';
export const GET_SAVED_PACKING_QUERY_SUCCESS = 'GET_SAVED_PACKING_QUERY_SUCCESS';
export const GET_SAVED_PACKING_QUERY_FAILURE = 'GET_SAVED_PACKING_QUERY_FAILURE';
