// Get data of selected model
export const GET_SUPPLIER_INVOICE = "GET_SUPPLIER_INVOICE";
export const GET_SUPPLIER_INVOICE_SUCCESS = "GET_SUPPLIER_INVOICE_SUCCESS";
export const GET_SUPPLIER_INVOICE_FAILURE = "GET_SUPPLIER_INVOICE_FAILURE";

// Get data of selected model
export const SET_SUPPLIER_INVOICE = "SET_SUPPLIER_INVOICE";
export const SET_SUPPLIER_INVOICE_SUCCESS = "SET_SUPPLIER_INVOICE_SUCCESS";
export const SET_SUPPLIER_INVOICE_FAILURE = "SET_SUPPLIER_INVOICE_FAILURE";

// GET DETAILS
export const GET_SUPPLIER_INVOICE_DETAILS = "GET_SUPPLIER_INVOICE_DETAILS";
export const GET_SUPPLIER_INVOICE_DETAILS_SUCCESS = "GET_SUPPLIER_INVOICE_DETAILS_SUCCESS";
export const GET_SUPPLIER_INVOICE_DETAILS_FAILURE = "GET_SUPPLIER_INVOICE_DETAILS_FAILURE";

// GET FILTERS
export const GET_FILTER_SUPPLIER_INVOICE = "GET_FILTER_SUPPLIER_INVOICE";
export const GET_FILTER_SUPPLIER_INVOICE_SUCCESS = "GET_FILTER_SUPPLIER_INVOICE_SUCCESS";
export const GET_FILTER_SUPPLIER_INVOICE_FAILURE = "GET_FILTER_SUPPLIER_INVOICE_FAILURE";

// DELETE SUPPLIER_INVOICE
export const DELETE_SUPPLIER_INVOICE = "DELETE_SUPPLIER_INVOICE";
export const DELETE_SUPPLIER_INVOICE_SUCCESS = "DELETE_SUPPLIER_INVOICE_SUCCESS";
export const DELETE_SUPPLIER_INVOICE_FAILURE = "DELETE_SUPPLIER_INVOICE_FAILURE";

// SET DUPLICATE
export const SET_DUPLICATE = "SET_DUPLICATE";
export const SET_DUPLICATE_SUCCESS = "SET_DUPLICATE_SUCCESS";
export const SET_DUPLICATE_FAILURE = "SET_DUPLICATE_FAILURE";

// CLEAR DUPLICATE
export const CLEAR_DUPLICATE = "CLEAR_DUPLICATE";
export const CLEAR_DUPLICATE_SUCCESS = "CLEAR_DUPLICATE_SUCCESS";
export const CLEAR_DUPLICATE_FAILURE = "CLEAR_DUPLICATE_FAILURE";

//get single invoice
export const GET_SINGLE_SUPPLIER_INVOICE_REQUEST = "GET_SINGLE_SUPPLIER_INVOICE_REQUEST";
export const GET_SINGLE_SUPPLIER_INVOICE_REQUEST_SUCCESS = "GET_SINGLE_SUPPLIER_INVOICE_REQUEST_SUCCESS";
export const GET_SINGLE_SUPPLIER_INVOICE_REQUEST_FAILURE = "GET_SINGLE_SUPPLIER_INVOICE_REQUEST_FAILURE";

//patch single invoice
export const PATCH_SINGLE_SUPPLIER_INVOICE = "PATCH_SINGLE_SUPPLIER_INVOICE";
export const PATCH_SINGLE_SUPPLIER_INVOICE_SUCCESS = "PATCH_SINGLE_SUPPLIER_INVOICE_SUCCESS";
export const PATCH_SINGLE_SUPPLIER_INVOICE_FAILURE = "PATCH_SINGLE_SUPPLIER_INVOICE_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_SUPPLIER_INVOICE_QUERY = 'GET_SAVED_SUPPLIER_INVOICE_QUERY';
export const GET_SAVED_SUPPLIER_INVOICE_QUERY_SUCCESS = 'GET_SAVED_SUPPLIER_INVOICE_QUERY_SUCCESS';
export const GET_SAVED_SUPPLIER_INVOICE_QUERY_FAILURE = 'GET_SAVED_SUPPLIER_INVOICE_QUERY_FAILURE';