// GET all PAYMENT TERMs
export const GET_ALL_PAYMENT_TERMS = "GET_ALL_PAYMENT_TERMS";
export const GET_ALL_PAYMENT_TERMS_SUCCESS = "GET_ALL_PAYMENT_TERMS_SUCCESS";
export const GET_ALL_PAYMENT_TERMS_FAILURE = "GET_ALL_PAYMENT_TERMS_FAILURE";

// GET one PAYMENT TERM
export const GET_PAYMENT_TERM = "GET_PAYMENT_TERM";
export const GET_PAYMENT_TERM_SUCCESS = "GET_PAYMENT_TERM_SUCCESS";
export const GET_PAYMENT_TERM_FAILURE = "GET_PAYMENT_TERM_FAILURE";

// POST one PAYMENT TERM 
export const POST_PAYMENT_TERM = "POST_PAYMENT_TERM";
export const POST_PAYMENT_TERM_SUCCESS = "POST_PAYMENT_TERM_SUCCESS";
export const POST_PAYMENT_TERM_FAILURE = "POST_PAYMENT_TERM_FAILURE";

// PATCH one PAYMENT TERM 
export const PATCH_PAYMENT_TERM = "PATCH_PAYMENT_TERM";
export const PATCH_PAYMENT_TERM_SUCCESS = "PATCH_PAYMENT_TERM_SUCCESS";
export const PATCH_PAYMENT_TERM_FAILURE = "PATCH_PAYMENT_TERM_FAILURE";

// DELETE one PAYMENT TERM  
export const DELETE_PAYMENT_TERM = "DELETE_PAYMENT_TERM";
export const DELETE_PAYMENT_TERM_SUCCESS = "DELETE_PAYMENT_TERM_SUCCESS";
export const DELETE_PAYMENT_TERM_FAILURE = "DELETE_PAYMENT_TERM_FAILURE";
