
//GET ALL ROLES
export const GET_ALL_USER_ROLES = "GET_ALL_USER_ROLES";
export const GET_ALL_USER_ROLES_SUCCESS = "GET_ALL_USER_ROLES_SUCCESS";
export const GET_ALL_USER_ROLES_FAILURE = "GET_ALL_USER_ROLES_FAILURE";

// CREATE NEW ROLE 
export const POST_USER_ROLE = "POST_USER_ROLE";
export const POST_USER_ROLE_SUCCESS = "POST_USER_ROLE_SUCCESS";
export const POST_USER_ROLE_FAILURE = "POST_USER_ROLE_FAILURE";

//GET ROLE
export const GET_USER_ROLE = "GET_USER_ROLE";
export const GET_USER_ROLE_SUCCESS = "GET_USER_ROLE_SUCCESS";
export const GET_USER_ROLE_FAILURE = "GET_USER_ROLE_FAILURE";

//PATCH
export const PATCH_USER_ROLE = "PATCH_USER_ROLE";
export const PATCH_USER_ROLE_SUCCESS = "PATCH_USER_ROLE_SUCCESS";
export const PATCH_USER_ROLE_FAILURE = "PATCH_USER_ROLE_FAILURE";

//DELETE 
export const DELETE_USER_ROLE = "DELETE_USER_ROLE";
export const DELETE_USER_ROLE_SUCCESS = "DELETE_USER_ROLE_SUCCESS";
export const DELETE_USER_ROLE_FAILURE = "DELETE_USER_ROLE_FAILURE";

