// Get all work orders 
export const GET_ALL_WORKORDER = 'GET_ALL_WORKORDER'
export const GET_ALL_WORKORDER_SUCCESS = 'GET_ALL_WORKORDER_SUCCESS'
export const GET_ALL_WORKORDER_FAILURE = 'GET_ALL_WORKORDER_FAILURE'

export const GET_FILTER_WORKORDER_REQUEST = 'GET_FILTER_WORKORDER_REQUEST'
export const GET_FILTER_WORKORDER_SUCCESS = 'GET_FILTER_WORKORDER_SUCCESS'
export const GET_FILTER_WORKORDER_FAILURE = 'GET_FILTER_WORKORDER_FAILURE'

// Get single work order 
export const GET_WORKORDER = 'GET_WORKORDER';
export const GET_WORKORDER_SUCCESS = 'GET_WORKORDER_SUCCESS';
export const GET_WORKORDER_FAILURE = 'GET_WORKORDER_FAILURE';

// update work order item 
export const SET_WORKORDER_ITEM = 'SET_WORKORDER_ITEM';
export const SET_WORKORDER_ITEM_SUCCESS = 'SET_WORKORDER_ITEM_SUCCESS';
export const SET_WORKORDER_ITEM_FAILURE = 'SET_WORKORDER_ITEM_FAILURE';

// update work order item description
export const SET_WORKORDER_ITEM_DESCRIPTION = 'SET_WORKORDER_ITEM_DESCRIPTION';
export const SET_WORKORDER_ITEM_DESCRIPTION_SUCCESS = 'SET_WORKORDER_ITEM_DESCRIPTION_SUCCESS';
export const SET_WORKORDER_ITEM_DESCRIPTION_FAILURE = 'SET_WORKORDER_ITEM_DESCRIPTION_FAILURE';

export const SET_WORKORDER = 'SET_WORKORDER';
export const SET_WORKORDER_SUCCESS = 'SET_WORKORDER_SUCCESS';
export const SET_WORKORDER_FAILURE = 'SET_WORKORDER_FAILURE';

// find completed WO by soId 
export const GET_WO_BY_SOID = 'GET_WO_BY_SOID';
export const GET_WO_BY_SOID_SUCCESS = 'GET_WO_BY_SOID_SUCCESS';
export const GET_WO_BY_SOID_FAILURE = 'GET_WO_BY_SOID_FAILURE';

// pdf
export const PDF_CREATE_WORKER_ORDER ='PDF_CREATE_WORKER_ORDER';
export const PDF_CREATE_WORKER_ORDER_SUCCESS ='PDF_CREATE_WORKER_ORDER_SUCCESS';
export const PDF_CREATE_WORKER_ORDER_FAILURE ='PDF_CREATE_WORKER_ORDER_FAILURE';

// post checked sku
export const POST_CHECKED_SKU ="POST_CHECKED_SKU";
export const POST_CHECKED_SKU_SUCCESS ="POST_CHECKED_SKU_SUCCESS";
export const POST_CHECKED_SKU_FAILURE ="POST_CHECKED_SKU_FAILURE";

// update workordder from post checked sku 
export const UPDATE_WO_POST_CHECKED_SKU ="UPDATE_WO_POST_CHECKED_SKU";
export const UPDATE_WO_POST_CHECKED_SKU_SUCCESS ="UPDATE_WO_POST_CHECKED_SKU_SUCCESS";
export const UPDATE_WO_POST_CHECKED_SKU_FAILURE ="UPDATE_WO_POST_CHECKED_SKU_FAILURE";

//SAVE QUERIES 
export const GET_SAVED_WORKORDER_QUERY = 'GET_SAVED_WORKORDER_QUERY';
export const GET_SAVED_WORKORDER_QUERY_SUCCESS = 'GET_SAVED_WORKORDER_QUERY_SUCCESS';
export const GET_SAVED_WORKORDER_QUERY_FAILURE = 'GET_SAVED_WORKORDER_QUERY_FAILURE';

//Light Reset Workorder 
export const PATCH_LIGHT_RESET_WORKORDER = "PATCH_LIGHT_RESET_WORKORDER"
export const PATCH_LIGHT_RESET_WORKORDER_SUCCESS = "PATCH_LIGHT_RESET_WORKORDER_SUCCESS"
export const PATCH_LIGHT_RESET_WORKORDER_FAILURE = "PATCH_LIGHT_RESET_WORKORDER_FAILURE"

//Medium Reset Workorder 
export const PATCH_MEDIUM_RESET_WORKORDER = "PATCH_MEDIUM_RESET_WORKORDER"
export const PATCH_MEDIUM_RESET_WORKORDER_SUCCESS = "PATCH_MEDIUM_RESET_WORKORDER_SUCCESS"
export const PATCH_MEDIUM_RESET_WORKORDER_FAILURE = "PATCH_MEDIUM_RESET_WORKORDER_FAILURE"
