// GET all GRP ONE 
export const GET_ALL_GRP_ONE_SETTINGS = "GET_ALL_GRP_ONE_SETTINGS";
export const GET_ALL_GRP_ONE_SETTINGS_SUCCESS = "GET_ALL_GRP_ONE_SETTINGS_SUCCESS";
export const GET_ALL_GRP_ONE_SETTINGS_FAILURE = "GET_ALL_GRP_ONE_SETTINGS_FAILURE";

// GET one GRP ONE 
export const GET_GRP_ONE_SETTING = "GET_GRP_ONE_SETTING";
export const GET_GRP_ONE_SETTING_SUCCESS = "GET_GRP_ONE_SETTING_SUCCESS";
export const GET_GRP_ONE_SETTING_FAILURE = "GET_GRP_ONE_SETTING_FAILURE";

// POST one GRP ONE 
export const POST_GRP_ONE_SETTING = "POST_GRP_ONE_SETTING";
export const POST_GRP_ONE_SETTING_SUCCESS = "POST_GRP_ONE_SETTING_SUCCESS";
export const POST_GRP_ONE_SETTING_FAILURE = "POST_GRP_ONE_SETTING_FAILURE";

// PUT one GRP ONE 
export const PUT_GRP_ONE_SETTING = "PUT_GRP_ONE_SETTING";
export const PUT_GRP_ONE_SETTING_SUCCESS = "PUT_GRP_ONE_SETTING_SUCCESS";
export const PUT_GRP_ONE_SETTING_FAILURE = "PUT_GRP_ONE_SETTING_FAILURE";

// DELETE one GRP ONE
export const DELETE_GRP_ONE_SETTING = "DELETE_GRP_ONE_SETTING";
export const DELETE_GRP_ONE_SETTING_SUCCESS = "DELETE_GRP_ONE_SETTING_SUCCESS";
export const DELETE_GRP_ONE_SETTING_FAILURE = "DELETE_GRP_ONE_SETTING_FAILURE";




// GET all GRP TWO 
export const GET_ALL_GRP_TWO_SETTINGS = "GET_ALL_GRP_TWO_SETTINGS";
export const GET_ALL_GRP_TWO_SETTINGS_SUCCESS = "GET_ALL_GRP_TWO_SETTINGS_SUCCESS";
export const GET_ALL_GRP_TWO_SETTINGS_FAILURE = "GET_ALL_GRP_TWO_SETTINGS_FAILURE";

// GET one GRP TWO 
export const GET_GRP_TWO_SETTING = "GET_GRP_TWO_SETTING";
export const GET_GRP_TWO_SETTING_SUCCESS = "GET_GRP_TWO_SETTING_SUCCESS";
export const GET_GRP_TWO_SETTING_FAILURE = "GET_GRP_TWO_SETTING_FAILURE";

// POST one GRP TWO 
export const POST_GRP_TWO_SETTING = "POST_GRP_TWO_SETTING";
export const POST_GRP_TWO_SETTING_SUCCESS = "POST_GRP_TWO_SETTING_SUCCESS";
export const POST_GRP_TWO_SETTING_FAILURE = "POST_GRP_TWO_SETTING_FAILURE";

// PUT one GRP TWO 
export const PUT_GRP_TWO_SETTING = "PUT_GRP_TWO_SETTING";
export const PUT_GRP_TWO_SETTING_SUCCESS = "PUT_GRP_TWO_SETTING_SUCCESS";
export const PUT_GRP_TWO_SETTING_FAILURE = "PUT_GRP_TWO_SETTING_FAILURE";

// DELETE one GRP TWO
export const DELETE_GRP_TWO_SETTING = "DELETE_GRP_TWO_SETTING";
export const DELETE_GRP_TWO_SETTING_SUCCESS = "DELETE_GRP_TWO_SETTING_SUCCESS";
export const DELETE_GRP_TWO_SETTING_FAILURE = "DELETE_GRP_TWO_SETTING_FAILURE";




// GET all SIZE
export const GET_ALL_SIZE_SETTINGS = "GET_ALL_SIZE_SETTINGS";
export const GET_ALL_SIZE_SETTINGS_SUCCESS = "GET_ALL_SIZE_SETTINGS_SUCCESS";
export const GET_ALL_SIZE_SETTINGS_FAILURE = "GET_ALL_SIZE_SETTINGS_FAILURE";

// GET one SIZE
export const GET_SIZE_SETTING = "GET_SIZE_SETTING";
export const GET_SIZE_SETTING_SUCCESS = "GET_SIZE_SETTING_SUCCESS";
export const GET_SIZE_SETTING_FAILURE = "GET_SIZE_SETTING_FAILURE";

// POST one SIZE
export const POST_SIZE_SETTING = "POST_SIZE_SETTING";
export const POST_SIZE_SETTING_SUCCESS = "POST_SIZE_SETTING_SUCCESS";
export const POST_SIZE_SETTING_FAILURE = "POST_SIZE_SETTING_FAILURE";

// PUT one SIZE
export const PUT_SIZE_SETTING = "PUT_SIZE_SETTING";
export const PUT_SIZE_SETTING_SUCCESS = "PUT_SIZE_SETTING_SUCCESS";
export const PUT_SIZE_SETTING_FAILURE = "PUT_SIZE_SETTING_FAILURE";

// DELETE one SIZE
export const DELETE_SIZE_SETTING = "DELETE_SIZE_SETTING";
export const DELETE_SIZE_SETTING_SUCCESS = "DELETE_SIZE_SETTING_SUCCESS";
export const DELETE_SIZE_SETTING_FAILURE = "DELETE_SIZE_SETTING_FAILURE";




// GET all MATERIAL
export const GET_ALL_MATERIAL_SETTINGS = "GET_ALL_MATERIAL_SETTINGS";
export const GET_ALL_MATERIAL_SETTINGS_SUCCESS = "GET_ALL_MATERIAL_SETTINGS_SUCCESS";
export const GET_ALL_MATERIAL_SETTINGS_FAILURE = "GET_ALL_MATERIAL_SETTINGS_FAILURE";

// GET one MATERIAL
export const GET_MATERIAL_SETTING = "GET_MATERIAL_SETTING";
export const GET_MATERIAL_SETTING_SUCCESS = "GET_MATERIAL_SETTING_SUCCESS";
export const GET_MATERIAL_SETTING_FAILURE = "GET_MATERIAL_SETTING_FAILURE";

// POST one MATERIAL
export const POST_MATERIAL_SETTING = "POST_MATERIAL_SETTING";
export const POST_MATERIAL_SETTING_SUCCESS = "POST_MATERIAL_SETTING_SUCCESS";
export const POST_MATERIAL_SETTING_FAILURE = "POST_MATERIAL_SETTING_FAILURE";

// PUT one MATERIAL
export const PUT_MATERIAL_SETTING = "PUT_MATERIAL_SETTING";
export const PUT_MATERIAL_SETTING_SUCCESS = "PUT_MATERIAL_SETTING_SUCCESS";
export const PUT_MATERIAL_SETTING_FAILURE = "PUT_MATERIAL_SETTING_FAILURE";

// DELETE one MATERIAL
export const DELETE_MATERIAL_SETTING = "DELETE_MATERIAL_SETTING";
export const DELETE_MATERIAL_SETTING_SUCCESS = "DELETE_MATERIAL_SETTING_SUCCESS";
export const DELETE_MATERIAL_SETTING_FAILURE = "DELETE_MATERIAL_SETTING_FAILURE";




// GET all BRAND
export const GET_ALL_BRAND_SETTINGS = "GET_ALL_BRAND_SETTINGS";
export const GET_ALL_BRAND_SETTINGS_SUCCESS = "GET_ALL_BRAND_SETTINGS_SUCCESS";
export const GET_ALL_BRAND_SETTINGS_FAILURE = "GET_ALL_BRAND_SETTINGS_FAILURE";

// GET one BRAND
export const GET_BRAND_SETTING = "GET_BRAND_SETTING";
export const GET_BRAND_SETTING_SUCCESS = "GET_BRAND_SETTING_SUCCESS";
export const GET_BRAND_SETTING_FAILURE = "GET_BRAND_SETTING_FAILURE";

// POST one BRAND
export const POST_BRAND_SETTING = "POST_BRAND_SETTING";
export const POST_BRAND_SETTING_SUCCESS = "POST_BRAND_SETTING_SUCCESS";
export const POST_BRAND_SETTING_FAILURE = "POST_BRAND_SETTING_FAILURE";

// PUT one BRAND
export const PUT_BRAND_SETTING = "PUT_BRAND_SETTING";
export const PUT_BRAND_SETTING_SUCCESS = "PUT_BRAND_SETTING_SUCCESS";
export const PUT_BRAND_SETTING_FAILURE = "PUT_BRAND_SETTING_FAILURE";

// DELETE one BRAND
export const DELETE_BRAND_SETTING = "DELETE_BRAND_SETTING";
export const DELETE_BRAND_SETTING_SUCCESS = "DELETE_BRAND_SETTING_SUCCESS";
export const DELETE_BRAND_SETTING_FAILURE = "DELETE_BRAND_SETTING_FAILURE";





// GET all UOM
export const GET_ALL_UOM_SETTINGS = "GET_ALL_UOM_SETTINGS";
export const GET_ALL_UOM_SETTINGS_SUCCESS = "GET_ALL_UOM_SETTINGS_SUCCESS";
export const GET_ALL_UOM_SETTINGS_FAILURE = "GET_ALL_UOM_SETTINGS_FAILURE";

// GET one UOM
export const GET_UOM_SETTING = "GET_UOM_SETTING";
export const GET_UOM_SETTING_SUCCESS = "GET_UOM_SETTING_SUCCESS";
export const GET_UOM_SETTING_FAILURE = "GET_UOM_SETTING_FAILURE";

// POST one UOM
export const POST_UOM_SETTING = "POST_UOM_SETTING";
export const POST_UOM_SETTING_SUCCESS = "POST_UOM_SETTING_SUCCESS";
export const POST_UOM_SETTING_FAILURE = "POST_UOM_SETTING_FAILURE";

// PUT one UOM
export const PUT_UOM_SETTING = "PUT_UOM_SETTING";
export const PUT_UOM_SETTING_SUCCESS = "PUT_UOM_SETTING_SUCCESS";
export const PUT_UOM_SETTING_FAILURE = "PUT_UOM_SETTING_FAILURE";

// DELETE one UOM
export const DELETE_UOM_SETTING = "DELETE_UOM_SETTING";
export const DELETE_UOM_SETTING_SUCCESS = "DELETE_UOM_SETTING_SUCCESS";
export const DELETE_UOM_SETTING_FAILURE = "DELETE_UOM_SETTING_FAILURE";