// GET all PAYMENT TERMs
export const GET_ALL_PROFIT_LOSS = "GET_ALL_PROFIT_LOSS";
export const GET_ALL_PROFIT_LOSS_SUCCESS = "GET_ALL_PROFIT_LOSS_SUCCESS";
export const GET_ALL_PROFIT_LOSS_FAILURE = "GET_ALL_PROFIT_LOSS_FAILURE";

// GET one PAYMENT TERM
export const GET_PROFIT_LOSS = "GET_PROFIT_LOSS";
export const GET_PROFIT_LOSS_SUCCESS = "GET_PROFIT_LOSS_SUCCESS";
export const GET_PROFIT_LOSS_FAILURE = "GET_PROFIT_LOSS_FAILURE";

// POST one PAYMENT TERM 
export const POST_PROFIT_LOSS = "POST_PROFIT_LOSS";
export const POST_PROFIT_LOSS_SUCCESS = "POST_PROFIT_LOSS_SUCCESS";
export const POST_PROFIT_LOSS_FAILURE = "POST_PROFIT_LOSS_FAILURE";

// PATCH one PAYMENT TERM 
export const PATCH_PROFIT_LOSS = "PATCH_PROFIT_LOSS";
export const PATCH_PROFIT_LOSS_SUCCESS = "PATCH_PROFIT_LOSS_SUCCESS";
export const PATCH_PROFIT_LOSS_FAILURE = "PATCH_PROFIT_LOSS_FAILURE";

// DELETE one PAYMENT TERM  
export const DELETE_PROFIT_LOSS = "DELETE_PROFIT_LOSS";
export const DELETE_PROFIT_LOSS_SUCCESS = "DELETE_PROFIT_LOSS_SUCCESS";
export const DELETE_PROFIT_LOSS_FAILURE = "DELETE_PROFIT_LOSS_FAILURE";